// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file alpha/registration.v1.proto (package reside.alpha.registration.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, StringValueJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file alpha/registration.v1.proto.
 */
export const file_alpha_registration_v1: GenFile = /*@__PURE__*/
  fileDesc("ChthbHBoYS9yZWdpc3RyYXRpb24udjEucHJvdG8SHHJlc2lkZS5hbHBoYS5yZWdpc3RyYXRpb24udjEiYQoVUmVwbGljYURlcGVuZGVuY3lTbG90EgwKBG5hbWUYASABKAkSOgoUZGVmYXVsdF9yZXBsaWNhX25hbWUYAiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUiZQodUmVwbGljYUVuZHBvaW50RGVwZW5kZW5jeVNsb3QSDAoEbmFtZRgBIAEoCRI2ChBkZWZhdWx0X2VuZHBvaW50GAIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlIs0DChZSZWdpc3RlclJlcGxpY2FSZXF1ZXN0Eg0KBXRpdGxlGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJEjAKCmF2YXRhcl91cmwYAyABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSGQoRaW50ZXJuYWxfZW5kcG9pbnQYBCABKAkSNQoPcHVibGljX2VuZHBvaW50GAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlElEKFHJlcGxpY2FfZGVwZW5kZW5jaWVzGAYgAygLMjMucmVzaWRlLmFscGhhLnJlZ2lzdHJhdGlvbi52MS5SZXBsaWNhRGVwZW5kZW5jeVNsb3QSWgoVZW5kcG9pbnRfZGVwZW5kZW5jaWVzGAcgAygLMjsucmVzaWRlLmFscGhhLnJlZ2lzdHJhdGlvbi52MS5SZXBsaWNhRW5kcG9pbnREZXBlbmRlbmN5U2xvdBItCgd2ZXJzaW9uGAggASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEi0KB2NoYW5nZXMYCSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUydgoTUmVnaXN0cmF0aW9uU2VydmljZRJfCg9SZWdpc3RlclJlcGxpY2ESNC5yZXNpZGUuYWxwaGEucmVnaXN0cmF0aW9uLnYxLlJlZ2lzdGVyUmVwbGljYVJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHliBnByb3RvMw", [file_google_protobuf_wrappers, file_google_protobuf_empty]);

/**
 * The message describing the dependency slot for the replica dependency.
 *
 * @generated from message reside.alpha.registration.v1.ReplicaDependencySlot
 */
export type ReplicaDependencySlot = Message<"reside.alpha.registration.v1.ReplicaDependencySlot"> & {
  /**
   * The name of the dependency slot.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The default name of the replica that occupies this slot.
   *
   * @generated from field: google.protobuf.StringValue default_replica_name = 2;
   */
  defaultReplicaName?: string;
};

/**
 * The message describing the dependency slot for the replica dependency.
 *
 * @generated from message reside.alpha.registration.v1.ReplicaDependencySlot
 */
export type ReplicaDependencySlotJson = {
  /**
   * The name of the dependency slot.
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * The default name of the replica that occupies this slot.
   *
   * @generated from field: google.protobuf.StringValue default_replica_name = 2;
   */
  defaultReplicaName?: StringValueJson;
};

/**
 * Describes the message reside.alpha.registration.v1.ReplicaDependencySlot.
 * Use `create(ReplicaDependencySlotSchema)` to create a new message.
 */
export const ReplicaDependencySlotSchema: GenMessage<ReplicaDependencySlot, {jsonType: ReplicaDependencySlotJson}> = /*@__PURE__*/
  messageDesc(file_alpha_registration_v1, 0);

/**
 * The message describing the dependency slot for the replica endpoint.
 *
 * @generated from message reside.alpha.registration.v1.ReplicaEndpointDependencySlot
 */
export type ReplicaEndpointDependencySlot = Message<"reside.alpha.registration.v1.ReplicaEndpointDependencySlot"> & {
  /**
   * The name of the dependency slot.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The default value of the endpoint.
   *
   * @generated from field: google.protobuf.StringValue default_endpoint = 2;
   */
  defaultEndpoint?: string;
};

/**
 * The message describing the dependency slot for the replica endpoint.
 *
 * @generated from message reside.alpha.registration.v1.ReplicaEndpointDependencySlot
 */
export type ReplicaEndpointDependencySlotJson = {
  /**
   * The name of the dependency slot.
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * The default value of the endpoint.
   *
   * @generated from field: google.protobuf.StringValue default_endpoint = 2;
   */
  defaultEndpoint?: StringValueJson;
};

/**
 * Describes the message reside.alpha.registration.v1.ReplicaEndpointDependencySlot.
 * Use `create(ReplicaEndpointDependencySlotSchema)` to create a new message.
 */
export const ReplicaEndpointDependencySlotSchema: GenMessage<ReplicaEndpointDependencySlot, {jsonType: ReplicaEndpointDependencySlotJson}> = /*@__PURE__*/
  messageDesc(file_alpha_registration_v1, 1);

/**
 * The request message for registering a new replica in Alpha Replica.
 * Must be auhenticated with Kubernetes SA.
 *
 * @generated from message reside.alpha.registration.v1.RegisterReplicaRequest
 */
export type RegisterReplicaRequest = Message<"reside.alpha.registration.v1.RegisterReplicaRequest"> & {
  /**
   * The required human-readable name of the replica.
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * The optional description of the replica.
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * The url of the replica avatar if any.
   *
   * @generated from field: google.protobuf.StringValue avatar_url = 3;
   */
  avatarUrl?: string;

  /**
   * The current internal endpoint of the replica.
   *
   * @generated from field: string internal_endpoint = 4;
   */
  internalEndpoint: string;

  /**
   * The current public endpoint of the replica if any.
   *
   * @generated from field: google.protobuf.StringValue public_endpoint = 5;
   */
  publicEndpoint?: string;

  /**
   * The list of dependency slots for other replicas that this replica requires to function properly.
   *
   * @generated from field: repeated reside.alpha.registration.v1.ReplicaDependencySlot replica_dependencies = 6;
   */
  replicaDependencies: ReplicaDependencySlot[];

  /**
   * The list of dependency slots for endpoints that this replica requires to function properly.
   * If endpoint value is not provided or overriden and matching resolved replica dependency slot is occupied,
   * the endpoint value from the occupied replica will be used.
   *
   * @generated from field: repeated reside.alpha.registration.v1.ReplicaEndpointDependencySlot endpoint_dependencies = 7;
   */
  endpointDependencies: ReplicaEndpointDependencySlot[];

  /**
   * The optional semantic version of the replica.
   *
   * @generated from field: google.protobuf.StringValue version = 8;
   */
  version?: string;

  /**
   * The optional latest changelog entry for the current replica version.
   *
   * @generated from field: google.protobuf.StringValue changes = 9;
   */
  changes?: string;
};

/**
 * The request message for registering a new replica in Alpha Replica.
 * Must be auhenticated with Kubernetes SA.
 *
 * @generated from message reside.alpha.registration.v1.RegisterReplicaRequest
 */
export type RegisterReplicaRequestJson = {
  /**
   * The required human-readable name of the replica.
   *
   * @generated from field: string title = 1;
   */
  title?: string;

  /**
   * The optional description of the replica.
   *
   * @generated from field: string description = 2;
   */
  description?: string;

  /**
   * The url of the replica avatar if any.
   *
   * @generated from field: google.protobuf.StringValue avatar_url = 3;
   */
  avatarUrl?: StringValueJson;

  /**
   * The current internal endpoint of the replica.
   *
   * @generated from field: string internal_endpoint = 4;
   */
  internalEndpoint?: string;

  /**
   * The current public endpoint of the replica if any.
   *
   * @generated from field: google.protobuf.StringValue public_endpoint = 5;
   */
  publicEndpoint?: StringValueJson;

  /**
   * The list of dependency slots for other replicas that this replica requires to function properly.
   *
   * @generated from field: repeated reside.alpha.registration.v1.ReplicaDependencySlot replica_dependencies = 6;
   */
  replicaDependencies?: ReplicaDependencySlotJson[];

  /**
   * The list of dependency slots for endpoints that this replica requires to function properly.
   * If endpoint value is not provided or overriden and matching resolved replica dependency slot is occupied,
   * the endpoint value from the occupied replica will be used.
   *
   * @generated from field: repeated reside.alpha.registration.v1.ReplicaEndpointDependencySlot endpoint_dependencies = 7;
   */
  endpointDependencies?: ReplicaEndpointDependencySlotJson[];

  /**
   * The optional semantic version of the replica.
   *
   * @generated from field: google.protobuf.StringValue version = 8;
   */
  version?: StringValueJson;

  /**
   * The optional latest changelog entry for the current replica version.
   *
   * @generated from field: google.protobuf.StringValue changes = 9;
   */
  changes?: StringValueJson;
};

/**
 * Describes the message reside.alpha.registration.v1.RegisterReplicaRequest.
 * Use `create(RegisterReplicaRequestSchema)` to create a new message.
 */
export const RegisterReplicaRequestSchema: GenMessage<RegisterReplicaRequest, {jsonType: RegisterReplicaRequestJson}> = /*@__PURE__*/
  messageDesc(file_alpha_registration_v1, 2);

/**
 * The service that must be used by all replicas to register themselves in the cluster.
 *
 * @generated from service reside.alpha.registration.v1.RegistrationService
 */
export const RegistrationService: GenService<{
  /**
   * RegisterReplica registers a new replica and its identity in Alpha.
   *
   * @generated from rpc reside.alpha.registration.v1.RegistrationService.RegisterReplica
   */
  registerReplica: {
    methodKind: "unary";
    input: typeof RegisterReplicaRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_alpha_registration_v1, 0);

