// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file alpha/replica.v1.proto (package reside.alpha.replica.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { StringValueJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file alpha/replica.v1.proto.
 */
export const file_alpha_replica_v1: GenFile = /*@__PURE__*/
  fileDesc("ChZhbHBoYS9yZXBsaWNhLnYxLnByb3RvEhdyZXNpZGUuYWxwaGEucmVwbGljYS52MSKZAgoLUmVwbGljYUluZm8SCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRINCgV0aXRsZRgDIAEoCRIxCgtkZXNjcmlwdGlvbhgEIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIZChFpbnRlcm5hbF9lbmRwb2ludBgFIAEoCRI1Cg9wdWJsaWNfZW5kcG9pbnQYBiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSLQoHdmVyc2lvbhgHIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRItCgdjaGFuZ2VzGAggASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlIhUKE0xpc3RSZXBsaWNhc1JlcXVlc3QiTgoUTGlzdFJlcGxpY2FzUmVzcG9uc2USNgoIcmVwbGljYXMYASADKAsyJC5yZXNpZGUuYWxwaGEucmVwbGljYS52MS5SZXBsaWNhSW5mbzJ9Cg5SZXBsaWNhU2VydmljZRJrCgxMaXN0UmVwbGljYXMSLC5yZXNpZGUuYWxwaGEucmVwbGljYS52MS5MaXN0UmVwbGljYXNSZXF1ZXN0Gi0ucmVzaWRlLmFscGhhLnJlcGxpY2EudjEuTGlzdFJlcGxpY2FzUmVzcG9uc2ViBnByb3RvMw", [file_google_protobuf_wrappers]);

/**
 * The public information about a registered replica.
 *
 * @generated from message reside.alpha.replica.v1.ReplicaInfo
 */
export type ReplicaInfo = Message<"reside.alpha.replica.v1.ReplicaInfo"> & {
  /**
   * The numeric identifier of the replica.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * The technical name of the replica.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * The human-readable title of the replica.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * The optional description of the replica.
   *
   * @generated from field: google.protobuf.StringValue description = 4;
   */
  description?: string;

  /**
   * The current internal endpoint of the replica.
   *
   * @generated from field: string internal_endpoint = 5;
   */
  internalEndpoint: string;

  /**
   * The current public endpoint of the replica if any.
   *
   * @generated from field: google.protobuf.StringValue public_endpoint = 6;
   */
  publicEndpoint?: string;

  /**
   * The optional semantic version of the replica.
   *
   * @generated from field: google.protobuf.StringValue version = 7;
   */
  version?: string;

  /**
   * The optional latest changelog entry for the current replica version.
   *
   * @generated from field: google.protobuf.StringValue changes = 8;
   */
  changes?: string;
};

/**
 * The public information about a registered replica.
 *
 * @generated from message reside.alpha.replica.v1.ReplicaInfo
 */
export type ReplicaInfoJson = {
  /**
   * The numeric identifier of the replica.
   *
   * @generated from field: int32 id = 1;
   */
  id?: number;

  /**
   * The technical name of the replica.
   *
   * @generated from field: string name = 2;
   */
  name?: string;

  /**
   * The human-readable title of the replica.
   *
   * @generated from field: string title = 3;
   */
  title?: string;

  /**
   * The optional description of the replica.
   *
   * @generated from field: google.protobuf.StringValue description = 4;
   */
  description?: StringValueJson;

  /**
   * The current internal endpoint of the replica.
   *
   * @generated from field: string internal_endpoint = 5;
   */
  internalEndpoint?: string;

  /**
   * The current public endpoint of the replica if any.
   *
   * @generated from field: google.protobuf.StringValue public_endpoint = 6;
   */
  publicEndpoint?: StringValueJson;

  /**
   * The optional semantic version of the replica.
   *
   * @generated from field: google.protobuf.StringValue version = 7;
   */
  version?: StringValueJson;

  /**
   * The optional latest changelog entry for the current replica version.
   *
   * @generated from field: google.protobuf.StringValue changes = 8;
   */
  changes?: StringValueJson;
};

/**
 * Describes the message reside.alpha.replica.v1.ReplicaInfo.
 * Use `create(ReplicaInfoSchema)` to create a new message.
 */
export const ReplicaInfoSchema: GenMessage<ReplicaInfo, {jsonType: ReplicaInfoJson}> = /*@__PURE__*/
  messageDesc(file_alpha_replica_v1, 0);

/**
 * The request message for listing registered replicas.
 *
 * @generated from message reside.alpha.replica.v1.ListReplicasRequest
 */
export type ListReplicasRequest = Message<"reside.alpha.replica.v1.ListReplicasRequest"> & {
};

/**
 * The request message for listing registered replicas.
 *
 * @generated from message reside.alpha.replica.v1.ListReplicasRequest
 */
export type ListReplicasRequestJson = {
};

/**
 * Describes the message reside.alpha.replica.v1.ListReplicasRequest.
 * Use `create(ListReplicasRequestSchema)` to create a new message.
 */
export const ListReplicasRequestSchema: GenMessage<ListReplicasRequest, {jsonType: ListReplicasRequestJson}> = /*@__PURE__*/
  messageDesc(file_alpha_replica_v1, 1);

/**
 * The response containing registered replicas.
 *
 * @generated from message reside.alpha.replica.v1.ListReplicasResponse
 */
export type ListReplicasResponse = Message<"reside.alpha.replica.v1.ListReplicasResponse"> & {
  /**
   * The list of registered replicas.
   *
   * @generated from field: repeated reside.alpha.replica.v1.ReplicaInfo replicas = 1;
   */
  replicas: ReplicaInfo[];
};

/**
 * The response containing registered replicas.
 *
 * @generated from message reside.alpha.replica.v1.ListReplicasResponse
 */
export type ListReplicasResponseJson = {
  /**
   * The list of registered replicas.
   *
   * @generated from field: repeated reside.alpha.replica.v1.ReplicaInfo replicas = 1;
   */
  replicas?: ReplicaInfoJson[];
};

/**
 * Describes the message reside.alpha.replica.v1.ListReplicasResponse.
 * Use `create(ListReplicasResponseSchema)` to create a new message.
 */
export const ListReplicasResponseSchema: GenMessage<ListReplicasResponse, {jsonType: ListReplicasResponseJson}> = /*@__PURE__*/
  messageDesc(file_alpha_replica_v1, 2);

/**
 * The service exposing public replica registry information.
 *
 * @generated from service reside.alpha.replica.v1.ReplicaService
 */
export const ReplicaService: GenService<{
  /**
   * ListReplicas returns the public information about all registered replicas.
   *
   * @generated from rpc reside.alpha.replica.v1.ReplicaService.ListReplicas
   */
  listReplicas: {
    methodKind: "unary";
    input: typeof ListReplicasRequestSchema;
    output: typeof ListReplicasResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_alpha_replica_v1, 0);

