
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Operation
 * Represents a workflow-backed operation for a Temporal namespace or PostgreSQL database.
 */
export type Operation = Prisma.OperationModel
/**
 * Model PostgresDatabase
 * Represents PostgreSQL credentials for a replica database.
 */
export type PostgresDatabase = Prisma.PostgresDatabaseModel
/**
 * Model TemporalNamespace
 * Represents a Temporal namespace owned by a replica.
 */
export type TemporalNamespace = Prisma.TemporalNamespaceModel
