
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PermissionRequestSetItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PermissionRequestSetItem
 * Represents a requested permission item inside a permission request set.
 */
export type PermissionRequestSetItemModel = runtime.Types.Result.DefaultSelection<Prisma.$PermissionRequestSetItemPayload>

export type AggregatePermissionRequestSetItem = {
  _count: PermissionRequestSetItemCountAggregateOutputType | null
  _avg: PermissionRequestSetItemAvgAggregateOutputType | null
  _sum: PermissionRequestSetItemSumAggregateOutputType | null
  _min: PermissionRequestSetItemMinAggregateOutputType | null
  _max: PermissionRequestSetItemMaxAggregateOutputType | null
}

export type PermissionRequestSetItemAvgAggregateOutputType = {
  id: number | null
  requestSetId: number | null
  permissionId: number | null
}

export type PermissionRequestSetItemSumAggregateOutputType = {
  id: bigint | null
  requestSetId: number | null
  permissionId: number | null
}

export type PermissionRequestSetItemMinAggregateOutputType = {
  id: bigint | null
  requestSetId: number | null
  permissionId: number | null
  scope: string | null
}

export type PermissionRequestSetItemMaxAggregateOutputType = {
  id: bigint | null
  requestSetId: number | null
  permissionId: number | null
  scope: string | null
}

export type PermissionRequestSetItemCountAggregateOutputType = {
  id: number
  requestSetId: number
  permissionId: number
  scope: number
  _all: number
}


export type PermissionRequestSetItemAvgAggregateInputType = {
  id?: true
  requestSetId?: true
  permissionId?: true
}

export type PermissionRequestSetItemSumAggregateInputType = {
  id?: true
  requestSetId?: true
  permissionId?: true
}

export type PermissionRequestSetItemMinAggregateInputType = {
  id?: true
  requestSetId?: true
  permissionId?: true
  scope?: true
}

export type PermissionRequestSetItemMaxAggregateInputType = {
  id?: true
  requestSetId?: true
  permissionId?: true
  scope?: true
}

export type PermissionRequestSetItemCountAggregateInputType = {
  id?: true
  requestSetId?: true
  permissionId?: true
  scope?: true
  _all?: true
}

export type PermissionRequestSetItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PermissionRequestSetItem to aggregate.
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermissionRequestSetItems to fetch.
   */
  orderBy?: Prisma.PermissionRequestSetItemOrderByWithRelationInput | Prisma.PermissionRequestSetItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PermissionRequestSetItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermissionRequestSetItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermissionRequestSetItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PermissionRequestSetItems
  **/
  _count?: true | PermissionRequestSetItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PermissionRequestSetItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PermissionRequestSetItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PermissionRequestSetItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PermissionRequestSetItemMaxAggregateInputType
}

export type GetPermissionRequestSetItemAggregateType<T extends PermissionRequestSetItemAggregateArgs> = {
      [P in keyof T & keyof AggregatePermissionRequestSetItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePermissionRequestSetItem[P]>
    : Prisma.GetScalarType<T[P], AggregatePermissionRequestSetItem[P]>
}




export type PermissionRequestSetItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PermissionRequestSetItemWhereInput
  orderBy?: Prisma.PermissionRequestSetItemOrderByWithAggregationInput | Prisma.PermissionRequestSetItemOrderByWithAggregationInput[]
  by: Prisma.PermissionRequestSetItemScalarFieldEnum[] | Prisma.PermissionRequestSetItemScalarFieldEnum
  having?: Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PermissionRequestSetItemCountAggregateInputType | true
  _avg?: PermissionRequestSetItemAvgAggregateInputType
  _sum?: PermissionRequestSetItemSumAggregateInputType
  _min?: PermissionRequestSetItemMinAggregateInputType
  _max?: PermissionRequestSetItemMaxAggregateInputType
}

export type PermissionRequestSetItemGroupByOutputType = {
  id: bigint
  requestSetId: number
  permissionId: number
  scope: string | null
  _count: PermissionRequestSetItemCountAggregateOutputType | null
  _avg: PermissionRequestSetItemAvgAggregateOutputType | null
  _sum: PermissionRequestSetItemSumAggregateOutputType | null
  _min: PermissionRequestSetItemMinAggregateOutputType | null
  _max: PermissionRequestSetItemMaxAggregateOutputType | null
}

type GetPermissionRequestSetItemGroupByPayload<T extends PermissionRequestSetItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PermissionRequestSetItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PermissionRequestSetItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PermissionRequestSetItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PermissionRequestSetItemGroupByOutputType[P]>
      }
    >
  >



export type PermissionRequestSetItemWhereInput = {
  AND?: Prisma.PermissionRequestSetItemWhereInput | Prisma.PermissionRequestSetItemWhereInput[]
  OR?: Prisma.PermissionRequestSetItemWhereInput[]
  NOT?: Prisma.PermissionRequestSetItemWhereInput | Prisma.PermissionRequestSetItemWhereInput[]
  id?: Prisma.BigIntFilter<"PermissionRequestSetItem"> | bigint | number
  requestSetId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  permissionId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  scope?: Prisma.StringNullableFilter<"PermissionRequestSetItem"> | string | null
  requestSet?: Prisma.XOR<Prisma.PermissionRequestSetScalarRelationFilter, Prisma.PermissionRequestSetWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}

export type PermissionRequestSetItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  requestSet?: Prisma.PermissionRequestSetOrderByWithRelationInput
  permission?: Prisma.PermissionOrderByWithRelationInput
}

export type PermissionRequestSetItemWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  requestSetId_permissionId_scope?: Prisma.PermissionRequestSetItemRequestSetIdPermissionIdScopeCompoundUniqueInput
  AND?: Prisma.PermissionRequestSetItemWhereInput | Prisma.PermissionRequestSetItemWhereInput[]
  OR?: Prisma.PermissionRequestSetItemWhereInput[]
  NOT?: Prisma.PermissionRequestSetItemWhereInput | Prisma.PermissionRequestSetItemWhereInput[]
  requestSetId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  permissionId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  scope?: Prisma.StringNullableFilter<"PermissionRequestSetItem"> | string | null
  requestSet?: Prisma.XOR<Prisma.PermissionRequestSetScalarRelationFilter, Prisma.PermissionRequestSetWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}, "id" | "requestSetId_permissionId_scope">

export type PermissionRequestSetItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  scope?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PermissionRequestSetItemCountOrderByAggregateInput
  _avg?: Prisma.PermissionRequestSetItemAvgOrderByAggregateInput
  _max?: Prisma.PermissionRequestSetItemMaxOrderByAggregateInput
  _min?: Prisma.PermissionRequestSetItemMinOrderByAggregateInput
  _sum?: Prisma.PermissionRequestSetItemSumOrderByAggregateInput
}

export type PermissionRequestSetItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput | Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput | Prisma.PermissionRequestSetItemScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"PermissionRequestSetItem"> | bigint | number
  requestSetId?: Prisma.IntWithAggregatesFilter<"PermissionRequestSetItem"> | number
  permissionId?: Prisma.IntWithAggregatesFilter<"PermissionRequestSetItem"> | number
  scope?: Prisma.StringNullableWithAggregatesFilter<"PermissionRequestSetItem"> | string | null
}

export type PermissionRequestSetItemCreateInput = {
  id?: bigint | number
  scope?: string | null
  requestSet: Prisma.PermissionRequestSetCreateNestedOneWithoutItemsInput
  permission: Prisma.PermissionCreateNestedOneWithoutRequestSetItemsInput
}

export type PermissionRequestSetItemUncheckedCreateInput = {
  id?: bigint | number
  requestSetId: number
  permissionId: number
  scope?: string | null
}

export type PermissionRequestSetItemUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestSet?: Prisma.PermissionRequestSetUpdateOneRequiredWithoutItemsNestedInput
  permission?: Prisma.PermissionUpdateOneRequiredWithoutRequestSetItemsNestedInput
}

export type PermissionRequestSetItemUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestSetId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemCreateManyInput = {
  id?: bigint | number
  requestSetId: number
  permissionId: number
  scope?: string | null
}

export type PermissionRequestSetItemUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestSetId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemListRelationFilter = {
  every?: Prisma.PermissionRequestSetItemWhereInput
  some?: Prisma.PermissionRequestSetItemWhereInput
  none?: Prisma.PermissionRequestSetItemWhereInput
}

export type PermissionRequestSetItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PermissionRequestSetItemRequestSetIdPermissionIdScopeCompoundUniqueInput = {
  requestSetId: number
  permissionId: number
  scope: string
}

export type PermissionRequestSetItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  scope?: Prisma.SortOrder
}

export type PermissionRequestSetItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type PermissionRequestSetItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  scope?: Prisma.SortOrder
}

export type PermissionRequestSetItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  scope?: Prisma.SortOrder
}

export type PermissionRequestSetItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  requestSetId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type PermissionRequestSetItemCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput> | Prisma.PermissionRequestSetItemCreateWithoutPermissionInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyPermissionInputEnvelope
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
}

export type PermissionRequestSetItemUncheckedCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput> | Prisma.PermissionRequestSetItemCreateWithoutPermissionInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyPermissionInputEnvelope
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
}

export type PermissionRequestSetItemUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput> | Prisma.PermissionRequestSetItemCreateWithoutPermissionInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutPermissionInput | Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyPermissionInputEnvelope
  set?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  disconnect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  delete?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  update?: Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutPermissionInput | Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutPermissionInput | Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
}

export type PermissionRequestSetItemUncheckedUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput> | Prisma.PermissionRequestSetItemCreateWithoutPermissionInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutPermissionInput | Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyPermissionInputEnvelope
  set?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  disconnect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  delete?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  update?: Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutPermissionInput | Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutPermissionInput | Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
}

export type PermissionRequestSetItemCreateNestedManyWithoutRequestSetInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput> | Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyRequestSetInputEnvelope
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
}

export type PermissionRequestSetItemUncheckedCreateNestedManyWithoutRequestSetInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput> | Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyRequestSetInputEnvelope
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
}

export type PermissionRequestSetItemUpdateManyWithoutRequestSetNestedInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput> | Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput[]
  upsert?: Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutRequestSetInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyRequestSetInputEnvelope
  set?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  disconnect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  delete?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  update?: Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutRequestSetInput[]
  updateMany?: Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutRequestSetInput[]
  deleteMany?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
}

export type PermissionRequestSetItemUncheckedUpdateManyWithoutRequestSetNestedInput = {
  create?: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput> | Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput[] | Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput[]
  connectOrCreate?: Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput | Prisma.PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput[]
  upsert?: Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpsertWithWhereUniqueWithoutRequestSetInput[]
  createMany?: Prisma.PermissionRequestSetItemCreateManyRequestSetInputEnvelope
  set?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  disconnect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  delete?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  connect?: Prisma.PermissionRequestSetItemWhereUniqueInput | Prisma.PermissionRequestSetItemWhereUniqueInput[]
  update?: Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpdateWithWhereUniqueWithoutRequestSetInput[]
  updateMany?: Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutRequestSetInput | Prisma.PermissionRequestSetItemUpdateManyWithWhereWithoutRequestSetInput[]
  deleteMany?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
}

export type PermissionRequestSetItemCreateWithoutPermissionInput = {
  id?: bigint | number
  scope?: string | null
  requestSet: Prisma.PermissionRequestSetCreateNestedOneWithoutItemsInput
}

export type PermissionRequestSetItemUncheckedCreateWithoutPermissionInput = {
  id?: bigint | number
  requestSetId: number
  scope?: string | null
}

export type PermissionRequestSetItemCreateOrConnectWithoutPermissionInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  create: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput>
}

export type PermissionRequestSetItemCreateManyPermissionInputEnvelope = {
  data: Prisma.PermissionRequestSetItemCreateManyPermissionInput | Prisma.PermissionRequestSetItemCreateManyPermissionInput[]
  skipDuplicates?: boolean
}

export type PermissionRequestSetItemUpsertWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  update: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedUpdateWithoutPermissionInput>
  create: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutPermissionInput>
}

export type PermissionRequestSetItemUpdateWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateWithoutPermissionInput, Prisma.PermissionRequestSetItemUncheckedUpdateWithoutPermissionInput>
}

export type PermissionRequestSetItemUpdateManyWithWhereWithoutPermissionInput = {
  where: Prisma.PermissionRequestSetItemScalarWhereInput
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateManyMutationInput, Prisma.PermissionRequestSetItemUncheckedUpdateManyWithoutPermissionInput>
}

export type PermissionRequestSetItemScalarWhereInput = {
  AND?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
  OR?: Prisma.PermissionRequestSetItemScalarWhereInput[]
  NOT?: Prisma.PermissionRequestSetItemScalarWhereInput | Prisma.PermissionRequestSetItemScalarWhereInput[]
  id?: Prisma.BigIntFilter<"PermissionRequestSetItem"> | bigint | number
  requestSetId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  permissionId?: Prisma.IntFilter<"PermissionRequestSetItem"> | number
  scope?: Prisma.StringNullableFilter<"PermissionRequestSetItem"> | string | null
}

export type PermissionRequestSetItemCreateWithoutRequestSetInput = {
  id?: bigint | number
  scope?: string | null
  permission: Prisma.PermissionCreateNestedOneWithoutRequestSetItemsInput
}

export type PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput = {
  id?: bigint | number
  permissionId: number
  scope?: string | null
}

export type PermissionRequestSetItemCreateOrConnectWithoutRequestSetInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  create: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput>
}

export type PermissionRequestSetItemCreateManyRequestSetInputEnvelope = {
  data: Prisma.PermissionRequestSetItemCreateManyRequestSetInput | Prisma.PermissionRequestSetItemCreateManyRequestSetInput[]
  skipDuplicates?: boolean
}

export type PermissionRequestSetItemUpsertWithWhereUniqueWithoutRequestSetInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  update: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedUpdateWithoutRequestSetInput>
  create: Prisma.XOR<Prisma.PermissionRequestSetItemCreateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedCreateWithoutRequestSetInput>
}

export type PermissionRequestSetItemUpdateWithWhereUniqueWithoutRequestSetInput = {
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateWithoutRequestSetInput, Prisma.PermissionRequestSetItemUncheckedUpdateWithoutRequestSetInput>
}

export type PermissionRequestSetItemUpdateManyWithWhereWithoutRequestSetInput = {
  where: Prisma.PermissionRequestSetItemScalarWhereInput
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateManyMutationInput, Prisma.PermissionRequestSetItemUncheckedUpdateManyWithoutRequestSetInput>
}

export type PermissionRequestSetItemCreateManyPermissionInput = {
  id?: bigint | number
  requestSetId: number
  scope?: string | null
}

export type PermissionRequestSetItemUpdateWithoutPermissionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  requestSet?: Prisma.PermissionRequestSetUpdateOneRequiredWithoutItemsNestedInput
}

export type PermissionRequestSetItemUncheckedUpdateWithoutPermissionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestSetId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemUncheckedUpdateManyWithoutPermissionInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  requestSetId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemCreateManyRequestSetInput = {
  id?: bigint | number
  permissionId: number
  scope?: string | null
}

export type PermissionRequestSetItemUpdateWithoutRequestSetInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permission?: Prisma.PermissionUpdateOneRequiredWithoutRequestSetItemsNestedInput
}

export type PermissionRequestSetItemUncheckedUpdateWithoutRequestSetInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PermissionRequestSetItemUncheckedUpdateManyWithoutRequestSetInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  scope?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type PermissionRequestSetItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestSetId?: boolean
  permissionId?: boolean
  scope?: boolean
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permissionRequestSetItem"]>

export type PermissionRequestSetItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestSetId?: boolean
  permissionId?: boolean
  scope?: boolean
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permissionRequestSetItem"]>

export type PermissionRequestSetItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  requestSetId?: boolean
  permissionId?: boolean
  scope?: boolean
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["permissionRequestSetItem"]>

export type PermissionRequestSetItemSelectScalar = {
  id?: boolean
  requestSetId?: boolean
  permissionId?: boolean
  scope?: boolean
}

export type PermissionRequestSetItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "requestSetId" | "permissionId" | "scope", ExtArgs["result"]["permissionRequestSetItem"]>
export type PermissionRequestSetItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type PermissionRequestSetItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type PermissionRequestSetItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requestSet?: boolean | Prisma.PermissionRequestSetDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}

export type $PermissionRequestSetItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PermissionRequestSetItem"
  objects: {
    /**
     * The parent request set metadata.
     */
    requestSet: Prisma.$PermissionRequestSetPayload<ExtArgs>
    /**
     * The requested permission metadata.
     */
    permission: Prisma.$PermissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The unique identifier of the request set item.
     */
    id: bigint
    /**
     * The request set that owns this item.
     */
    requestSetId: number
    /**
     * The requested permission identifier.
     */
    permissionId: number
    /**
     * The optional descriptor of the requested scope.
     */
    scope: string | null
  }, ExtArgs["result"]["permissionRequestSetItem"]>
  composites: {}
}

export type PermissionRequestSetItemGetPayload<S extends boolean | null | undefined | PermissionRequestSetItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload, S>

export type PermissionRequestSetItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PermissionRequestSetItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PermissionRequestSetItemCountAggregateInputType | true
  }

export interface PermissionRequestSetItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PermissionRequestSetItem'], meta: { name: 'PermissionRequestSetItem' } }
  /**
   * Find zero or one PermissionRequestSetItem that matches the filter.
   * @param {PermissionRequestSetItemFindUniqueArgs} args - Arguments to find a PermissionRequestSetItem
   * @example
   * // Get one PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PermissionRequestSetItemFindUniqueArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PermissionRequestSetItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PermissionRequestSetItemFindUniqueOrThrowArgs} args - Arguments to find a PermissionRequestSetItem
   * @example
   * // Get one PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PermissionRequestSetItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PermissionRequestSetItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemFindFirstArgs} args - Arguments to find a PermissionRequestSetItem
   * @example
   * // Get one PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PermissionRequestSetItemFindFirstArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PermissionRequestSetItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemFindFirstOrThrowArgs} args - Arguments to find a PermissionRequestSetItem
   * @example
   * // Get one PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PermissionRequestSetItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PermissionRequestSetItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PermissionRequestSetItems
   * const permissionRequestSetItems = await prisma.permissionRequestSetItem.findMany()
   * 
   * // Get first 10 PermissionRequestSetItems
   * const permissionRequestSetItems = await prisma.permissionRequestSetItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const permissionRequestSetItemWithIdOnly = await prisma.permissionRequestSetItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PermissionRequestSetItemFindManyArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PermissionRequestSetItem.
   * @param {PermissionRequestSetItemCreateArgs} args - Arguments to create a PermissionRequestSetItem.
   * @example
   * // Create one PermissionRequestSetItem
   * const PermissionRequestSetItem = await prisma.permissionRequestSetItem.create({
   *   data: {
   *     // ... data to create a PermissionRequestSetItem
   *   }
   * })
   * 
   */
  create<T extends PermissionRequestSetItemCreateArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemCreateArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PermissionRequestSetItems.
   * @param {PermissionRequestSetItemCreateManyArgs} args - Arguments to create many PermissionRequestSetItems.
   * @example
   * // Create many PermissionRequestSetItems
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PermissionRequestSetItemCreateManyArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PermissionRequestSetItems and returns the data saved in the database.
   * @param {PermissionRequestSetItemCreateManyAndReturnArgs} args - Arguments to create many PermissionRequestSetItems.
   * @example
   * // Create many PermissionRequestSetItems
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PermissionRequestSetItems and only return the `id`
   * const permissionRequestSetItemWithIdOnly = await prisma.permissionRequestSetItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PermissionRequestSetItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PermissionRequestSetItem.
   * @param {PermissionRequestSetItemDeleteArgs} args - Arguments to delete one PermissionRequestSetItem.
   * @example
   * // Delete one PermissionRequestSetItem
   * const PermissionRequestSetItem = await prisma.permissionRequestSetItem.delete({
   *   where: {
   *     // ... filter to delete one PermissionRequestSetItem
   *   }
   * })
   * 
   */
  delete<T extends PermissionRequestSetItemDeleteArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemDeleteArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PermissionRequestSetItem.
   * @param {PermissionRequestSetItemUpdateArgs} args - Arguments to update one PermissionRequestSetItem.
   * @example
   * // Update one PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PermissionRequestSetItemUpdateArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemUpdateArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PermissionRequestSetItems.
   * @param {PermissionRequestSetItemDeleteManyArgs} args - Arguments to filter PermissionRequestSetItems to delete.
   * @example
   * // Delete a few PermissionRequestSetItems
   * const { count } = await prisma.permissionRequestSetItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PermissionRequestSetItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, PermissionRequestSetItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PermissionRequestSetItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PermissionRequestSetItems
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PermissionRequestSetItemUpdateManyArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PermissionRequestSetItems and returns the data updated in the database.
   * @param {PermissionRequestSetItemUpdateManyAndReturnArgs} args - Arguments to update many PermissionRequestSetItems.
   * @example
   * // Update many PermissionRequestSetItems
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PermissionRequestSetItems and only return the `id`
   * const permissionRequestSetItemWithIdOnly = await prisma.permissionRequestSetItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PermissionRequestSetItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PermissionRequestSetItem.
   * @param {PermissionRequestSetItemUpsertArgs} args - Arguments to update or create a PermissionRequestSetItem.
   * @example
   * // Update or create a PermissionRequestSetItem
   * const permissionRequestSetItem = await prisma.permissionRequestSetItem.upsert({
   *   create: {
   *     // ... data to create a PermissionRequestSetItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PermissionRequestSetItem we want to update
   *   }
   * })
   */
  upsert<T extends PermissionRequestSetItemUpsertArgs>(args: Prisma.SelectSubset<T, PermissionRequestSetItemUpsertArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetItemClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PermissionRequestSetItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemCountArgs} args - Arguments to filter PermissionRequestSetItems to count.
   * @example
   * // Count the number of PermissionRequestSetItems
   * const count = await prisma.permissionRequestSetItem.count({
   *   where: {
   *     // ... the filter for the PermissionRequestSetItems we want to count
   *   }
   * })
  **/
  count<T extends PermissionRequestSetItemCountArgs>(
    args?: Prisma.Subset<T, PermissionRequestSetItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PermissionRequestSetItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PermissionRequestSetItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PermissionRequestSetItemAggregateArgs>(args: Prisma.Subset<T, PermissionRequestSetItemAggregateArgs>): Prisma.PrismaPromise<GetPermissionRequestSetItemAggregateType<T>>

  /**
   * Group by PermissionRequestSetItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PermissionRequestSetItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PermissionRequestSetItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PermissionRequestSetItemGroupByArgs['orderBy'] }
      : { orderBy?: PermissionRequestSetItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PermissionRequestSetItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPermissionRequestSetItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PermissionRequestSetItem model
 */
readonly fields: PermissionRequestSetItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PermissionRequestSetItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PermissionRequestSetItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  requestSet<T extends Prisma.PermissionRequestSetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PermissionRequestSetDefaultArgs<ExtArgs>>): Prisma.Prisma__PermissionRequestSetClient<runtime.Types.Result.GetResult<Prisma.$PermissionRequestSetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  permission<T extends Prisma.PermissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PermissionDefaultArgs<ExtArgs>>): Prisma.Prisma__PermissionClient<runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PermissionRequestSetItem model
 */
export interface PermissionRequestSetItemFieldRefs {
  readonly id: Prisma.FieldRef<"PermissionRequestSetItem", 'BigInt'>
  readonly requestSetId: Prisma.FieldRef<"PermissionRequestSetItem", 'Int'>
  readonly permissionId: Prisma.FieldRef<"PermissionRequestSetItem", 'Int'>
  readonly scope: Prisma.FieldRef<"PermissionRequestSetItem", 'String'>
}
    

// Custom InputTypes
/**
 * PermissionRequestSetItem findUnique
 */
export type PermissionRequestSetItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter, which PermissionRequestSetItem to fetch.
   */
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
}

/**
 * PermissionRequestSetItem findUniqueOrThrow
 */
export type PermissionRequestSetItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter, which PermissionRequestSetItem to fetch.
   */
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
}

/**
 * PermissionRequestSetItem findFirst
 */
export type PermissionRequestSetItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter, which PermissionRequestSetItem to fetch.
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermissionRequestSetItems to fetch.
   */
  orderBy?: Prisma.PermissionRequestSetItemOrderByWithRelationInput | Prisma.PermissionRequestSetItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PermissionRequestSetItems.
   */
  cursor?: Prisma.PermissionRequestSetItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermissionRequestSetItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermissionRequestSetItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PermissionRequestSetItems.
   */
  distinct?: Prisma.PermissionRequestSetItemScalarFieldEnum | Prisma.PermissionRequestSetItemScalarFieldEnum[]
}

/**
 * PermissionRequestSetItem findFirstOrThrow
 */
export type PermissionRequestSetItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter, which PermissionRequestSetItem to fetch.
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermissionRequestSetItems to fetch.
   */
  orderBy?: Prisma.PermissionRequestSetItemOrderByWithRelationInput | Prisma.PermissionRequestSetItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PermissionRequestSetItems.
   */
  cursor?: Prisma.PermissionRequestSetItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermissionRequestSetItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermissionRequestSetItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PermissionRequestSetItems.
   */
  distinct?: Prisma.PermissionRequestSetItemScalarFieldEnum | Prisma.PermissionRequestSetItemScalarFieldEnum[]
}

/**
 * PermissionRequestSetItem findMany
 */
export type PermissionRequestSetItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter, which PermissionRequestSetItems to fetch.
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PermissionRequestSetItems to fetch.
   */
  orderBy?: Prisma.PermissionRequestSetItemOrderByWithRelationInput | Prisma.PermissionRequestSetItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PermissionRequestSetItems.
   */
  cursor?: Prisma.PermissionRequestSetItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PermissionRequestSetItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PermissionRequestSetItems.
   */
  skip?: number
  distinct?: Prisma.PermissionRequestSetItemScalarFieldEnum | Prisma.PermissionRequestSetItemScalarFieldEnum[]
}

/**
 * PermissionRequestSetItem create
 */
export type PermissionRequestSetItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * The data needed to create a PermissionRequestSetItem.
   */
  data: Prisma.XOR<Prisma.PermissionRequestSetItemCreateInput, Prisma.PermissionRequestSetItemUncheckedCreateInput>
}

/**
 * PermissionRequestSetItem createMany
 */
export type PermissionRequestSetItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PermissionRequestSetItems.
   */
  data: Prisma.PermissionRequestSetItemCreateManyInput | Prisma.PermissionRequestSetItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PermissionRequestSetItem createManyAndReturn
 */
export type PermissionRequestSetItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * The data used to create many PermissionRequestSetItems.
   */
  data: Prisma.PermissionRequestSetItemCreateManyInput | Prisma.PermissionRequestSetItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PermissionRequestSetItem update
 */
export type PermissionRequestSetItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * The data needed to update a PermissionRequestSetItem.
   */
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateInput, Prisma.PermissionRequestSetItemUncheckedUpdateInput>
  /**
   * Choose, which PermissionRequestSetItem to update.
   */
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
}

/**
 * PermissionRequestSetItem updateMany
 */
export type PermissionRequestSetItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PermissionRequestSetItems.
   */
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateManyMutationInput, Prisma.PermissionRequestSetItemUncheckedUpdateManyInput>
  /**
   * Filter which PermissionRequestSetItems to update
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * Limit how many PermissionRequestSetItems to update.
   */
  limit?: number
}

/**
 * PermissionRequestSetItem updateManyAndReturn
 */
export type PermissionRequestSetItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * The data used to update PermissionRequestSetItems.
   */
  data: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateManyMutationInput, Prisma.PermissionRequestSetItemUncheckedUpdateManyInput>
  /**
   * Filter which PermissionRequestSetItems to update
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * Limit how many PermissionRequestSetItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PermissionRequestSetItem upsert
 */
export type PermissionRequestSetItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * The filter to search for the PermissionRequestSetItem to update in case it exists.
   */
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
  /**
   * In case the PermissionRequestSetItem found by the `where` argument doesn't exist, create a new PermissionRequestSetItem with this data.
   */
  create: Prisma.XOR<Prisma.PermissionRequestSetItemCreateInput, Prisma.PermissionRequestSetItemUncheckedCreateInput>
  /**
   * In case the PermissionRequestSetItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PermissionRequestSetItemUpdateInput, Prisma.PermissionRequestSetItemUncheckedUpdateInput>
}

/**
 * PermissionRequestSetItem delete
 */
export type PermissionRequestSetItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
  /**
   * Filter which PermissionRequestSetItem to delete.
   */
  where: Prisma.PermissionRequestSetItemWhereUniqueInput
}

/**
 * PermissionRequestSetItem deleteMany
 */
export type PermissionRequestSetItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PermissionRequestSetItems to delete
   */
  where?: Prisma.PermissionRequestSetItemWhereInput
  /**
   * Limit how many PermissionRequestSetItems to delete.
   */
  limit?: number
}

/**
 * PermissionRequestSetItem without action
 */
export type PermissionRequestSetItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PermissionRequestSetItem
   */
  select?: Prisma.PermissionRequestSetItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PermissionRequestSetItem
   */
  omit?: Prisma.PermissionRequestSetItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PermissionRequestSetItemInclude<ExtArgs> | null
}
