// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none,json_types=true"
// @generated from file infra/vault.v1.proto (package reside.infra.vault.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file infra/vault.v1.proto.
 */
export const file_infra_vault_v1: GenFile = /*@__PURE__*/
  fileDesc("ChRpbmZyYS92YXVsdC52MS5wcm90bxIVcmVzaWRlLmluZnJhLnZhdWx0LnYxIjYKEFZhdWx0Q3JlZGVudGlhbHMSEAoIZW5kcG9pbnQYASABKAkSEAoIYXVkaWVuY2UYAiABKAkiVgobR2V0VmF1bHRDcmVkZW50aWFsc1Jlc3BvbnNlEjcKBnJlc3VsdBgBIAEoCzInLnJlc2lkZS5pbmZyYS52YXVsdC52MS5WYXVsdENyZWRlbnRpYWxzMnEKDFZhdWx0U2VydmljZRJhChNHZXRWYXVsdENyZWRlbnRpYWxzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjIucmVzaWRlLmluZnJhLnZhdWx0LnYxLkdldFZhdWx0Q3JlZGVudGlhbHNSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_empty]);

/**
 * The endpoint and Kubernetes token audience required to authenticate with Vault.
 *
 * @generated from message reside.infra.vault.v1.VaultCredentials
 */
export type VaultCredentials = Message<"reside.infra.vault.v1.VaultCredentials"> & {
  /**
   * The base URL of the Vault server.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * The Kubernetes TokenRequest audience accepted by Vault authentication.
   *
   * @generated from field: string audience = 2;
   */
  audience: string;
};

/**
 * The endpoint and Kubernetes token audience required to authenticate with Vault.
 *
 * @generated from message reside.infra.vault.v1.VaultCredentials
 */
export type VaultCredentialsJson = {
  /**
   * The base URL of the Vault server.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint?: string;

  /**
   * The Kubernetes TokenRequest audience accepted by Vault authentication.
   *
   * @generated from field: string audience = 2;
   */
  audience?: string;
};

/**
 * Describes the message reside.infra.vault.v1.VaultCredentials.
 * Use `create(VaultCredentialsSchema)` to create a new message.
 */
export const VaultCredentialsSchema: GenMessage<VaultCredentials, {jsonType: VaultCredentialsJson}> = /*@__PURE__*/
  messageDesc(file_infra_vault_v1, 0);

/**
 * The response for GetVaultCredentials request.
 *
 * @generated from message reside.infra.vault.v1.GetVaultCredentialsResponse
 */
export type GetVaultCredentialsResponse = Message<"reside.infra.vault.v1.GetVaultCredentialsResponse"> & {
  /**
   * @generated from field: reside.infra.vault.v1.VaultCredentials result = 1;
   */
  result?: VaultCredentials;
};

/**
 * The response for GetVaultCredentials request.
 *
 * @generated from message reside.infra.vault.v1.GetVaultCredentialsResponse
 */
export type GetVaultCredentialsResponseJson = {
  /**
   * @generated from field: reside.infra.vault.v1.VaultCredentials result = 1;
   */
  result?: VaultCredentialsJson;
};

/**
 * Describes the message reside.infra.vault.v1.GetVaultCredentialsResponse.
 * Use `create(GetVaultCredentialsResponseSchema)` to create a new message.
 */
export const GetVaultCredentialsResponseSchema: GenMessage<GetVaultCredentialsResponse, {jsonType: GetVaultCredentialsResponseJson}> = /*@__PURE__*/
  messageDesc(file_infra_vault_v1, 1);

/**
 * The service responsible for Vault runtime credentials.
 *
 * @generated from service reside.infra.vault.v1.VaultService
 */
export const VaultService: GenService<{
  /**
   * Gets Vault endpoint and authentication audience for the caller replica.
   *
   * @generated from rpc reside.infra.vault.v1.VaultService.GetVaultCredentials
   */
  getVaultCredentials: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetVaultCredentialsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_infra_vault_v1, 0);

