
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const OperationStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type OperationStatus = (typeof OperationStatus)[keyof typeof OperationStatus]


export const OperationType = {
  DELETE_SOURCE_CODE: 'DELETE_SOURCE_CODE'
} as const

export type OperationType = (typeof OperationType)[keyof typeof OperationType]


export const TaskStatus = {
  PLANNING: 'PLANNING',
  PLAN_READY: 'PLAN_READY',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REQUESTED_CANCELLATION: 'REQUESTED_CANCELLATION',
  CANCELLED: 'CANCELLED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const TaskPhase = {
  PLANNING: 'PLANNING',
  IMPLEMENTATION: 'IMPLEMENTATION'
} as const

export type TaskPhase = (typeof TaskPhase)[keyof typeof TaskPhase]
