
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
export const prismaVersion: PrismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  ApprovalRequest: 'ApprovalRequest',
  Avatar: 'Avatar',
  AvatarProvisionRequest: 'AvatarProvisionRequest',
  UnauthorizedAvatar: 'UnauthorizedAvatar',
  NotificationChannel: 'NotificationChannel',
  NotificationChannelBinding: 'NotificationChannelBinding',
  Chat: 'Chat',
  Command: 'Command',
  EncryptedContent: 'EncryptedContent',
  MemoryNote: 'MemoryNote',
  NaturalLanguageInteraction: 'NaturalLanguageInteraction',
  NotificationResponse: 'NotificationResponse',
  NotificationTopic: 'NotificationTopic',
  NotificationTaskGroup: 'NotificationTaskGroup',
  NotificationTask: 'NotificationTask',
  NotificationTaskPlanningPoll: 'NotificationTaskPlanningPoll',
  NotificationTaskPlanningPollOption: 'NotificationTaskPlanningPollOption',
  Notification: 'Notification',
  Operation: 'Operation',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "approvalRequest" | "avatar" | "avatarProvisionRequest" | "unauthorizedAvatar" | "notificationChannel" | "notificationChannelBinding" | "chat" | "command" | "encryptedContent" | "memoryNote" | "naturalLanguageInteraction" | "notificationResponse" | "notificationTopic" | "notificationTaskGroup" | "notificationTask" | "notificationTaskPlanningPoll" | "notificationTaskPlanningPollOption" | "notification" | "operation" | "user"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    ApprovalRequest: {
      payload: Prisma.$ApprovalRequestPayload<ExtArgs>
      fields: Prisma.ApprovalRequestFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ApprovalRequestFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ApprovalRequestFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        findFirst: {
          args: Prisma.ApprovalRequestFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ApprovalRequestFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        findMany: {
          args: Prisma.ApprovalRequestFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>[]
        }
        create: {
          args: Prisma.ApprovalRequestCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        createMany: {
          args: Prisma.ApprovalRequestCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ApprovalRequestCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>[]
        }
        delete: {
          args: Prisma.ApprovalRequestDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        update: {
          args: Prisma.ApprovalRequestUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        deleteMany: {
          args: Prisma.ApprovalRequestDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ApprovalRequestUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ApprovalRequestUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>[]
        }
        upsert: {
          args: Prisma.ApprovalRequestUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApprovalRequestPayload>
        }
        aggregate: {
          args: Prisma.ApprovalRequestAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateApprovalRequest>
        }
        groupBy: {
          args: Prisma.ApprovalRequestGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApprovalRequestGroupByOutputType>[]
        }
        count: {
          args: Prisma.ApprovalRequestCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApprovalRequestCountAggregateOutputType> | number
        }
      }
    }
    Avatar: {
      payload: Prisma.$AvatarPayload<ExtArgs>
      fields: Prisma.AvatarFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AvatarFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AvatarFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        findFirst: {
          args: Prisma.AvatarFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AvatarFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        findMany: {
          args: Prisma.AvatarFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>[]
        }
        create: {
          args: Prisma.AvatarCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        createMany: {
          args: Prisma.AvatarCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AvatarCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>[]
        }
        delete: {
          args: Prisma.AvatarDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        update: {
          args: Prisma.AvatarUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        deleteMany: {
          args: Prisma.AvatarDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AvatarUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AvatarUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>[]
        }
        upsert: {
          args: Prisma.AvatarUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarPayload>
        }
        aggregate: {
          args: Prisma.AvatarAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAvatar>
        }
        groupBy: {
          args: Prisma.AvatarGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvatarGroupByOutputType>[]
        }
        count: {
          args: Prisma.AvatarCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvatarCountAggregateOutputType> | number
        }
      }
    }
    AvatarProvisionRequest: {
      payload: Prisma.$AvatarProvisionRequestPayload<ExtArgs>
      fields: Prisma.AvatarProvisionRequestFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AvatarProvisionRequestFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AvatarProvisionRequestFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        findFirst: {
          args: Prisma.AvatarProvisionRequestFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AvatarProvisionRequestFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        findMany: {
          args: Prisma.AvatarProvisionRequestFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>[]
        }
        create: {
          args: Prisma.AvatarProvisionRequestCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        createMany: {
          args: Prisma.AvatarProvisionRequestCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AvatarProvisionRequestCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>[]
        }
        delete: {
          args: Prisma.AvatarProvisionRequestDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        update: {
          args: Prisma.AvatarProvisionRequestUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        deleteMany: {
          args: Prisma.AvatarProvisionRequestDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AvatarProvisionRequestUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AvatarProvisionRequestUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>[]
        }
        upsert: {
          args: Prisma.AvatarProvisionRequestUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AvatarProvisionRequestPayload>
        }
        aggregate: {
          args: Prisma.AvatarProvisionRequestAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAvatarProvisionRequest>
        }
        groupBy: {
          args: Prisma.AvatarProvisionRequestGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvatarProvisionRequestGroupByOutputType>[]
        }
        count: {
          args: Prisma.AvatarProvisionRequestCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AvatarProvisionRequestCountAggregateOutputType> | number
        }
      }
    }
    UnauthorizedAvatar: {
      payload: Prisma.$UnauthorizedAvatarPayload<ExtArgs>
      fields: Prisma.UnauthorizedAvatarFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UnauthorizedAvatarFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UnauthorizedAvatarFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        findFirst: {
          args: Prisma.UnauthorizedAvatarFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UnauthorizedAvatarFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        findMany: {
          args: Prisma.UnauthorizedAvatarFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>[]
        }
        create: {
          args: Prisma.UnauthorizedAvatarCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        createMany: {
          args: Prisma.UnauthorizedAvatarCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UnauthorizedAvatarCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>[]
        }
        delete: {
          args: Prisma.UnauthorizedAvatarDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        update: {
          args: Prisma.UnauthorizedAvatarUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        deleteMany: {
          args: Prisma.UnauthorizedAvatarDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UnauthorizedAvatarUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UnauthorizedAvatarUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>[]
        }
        upsert: {
          args: Prisma.UnauthorizedAvatarUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UnauthorizedAvatarPayload>
        }
        aggregate: {
          args: Prisma.UnauthorizedAvatarAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUnauthorizedAvatar>
        }
        groupBy: {
          args: Prisma.UnauthorizedAvatarGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnauthorizedAvatarGroupByOutputType>[]
        }
        count: {
          args: Prisma.UnauthorizedAvatarCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UnauthorizedAvatarCountAggregateOutputType> | number
        }
      }
    }
    NotificationChannel: {
      payload: Prisma.$NotificationChannelPayload<ExtArgs>
      fields: Prisma.NotificationChannelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationChannelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationChannelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        findFirst: {
          args: Prisma.NotificationChannelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationChannelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        findMany: {
          args: Prisma.NotificationChannelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        create: {
          args: Prisma.NotificationChannelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        createMany: {
          args: Prisma.NotificationChannelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationChannelCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        delete: {
          args: Prisma.NotificationChannelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        update: {
          args: Prisma.NotificationChannelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        deleteMany: {
          args: Prisma.NotificationChannelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationChannelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationChannelUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        upsert: {
          args: Prisma.NotificationChannelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        aggregate: {
          args: Prisma.NotificationChannelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationChannel>
        }
        groupBy: {
          args: Prisma.NotificationChannelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationChannelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelCountAggregateOutputType> | number
        }
      }
    }
    NotificationChannelBinding: {
      payload: Prisma.$NotificationChannelBindingPayload<ExtArgs>
      fields: Prisma.NotificationChannelBindingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationChannelBindingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationChannelBindingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        findFirst: {
          args: Prisma.NotificationChannelBindingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationChannelBindingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        findMany: {
          args: Prisma.NotificationChannelBindingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>[]
        }
        create: {
          args: Prisma.NotificationChannelBindingCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        createMany: {
          args: Prisma.NotificationChannelBindingCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationChannelBindingCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>[]
        }
        delete: {
          args: Prisma.NotificationChannelBindingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        update: {
          args: Prisma.NotificationChannelBindingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        deleteMany: {
          args: Prisma.NotificationChannelBindingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationChannelBindingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationChannelBindingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>[]
        }
        upsert: {
          args: Prisma.NotificationChannelBindingUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelBindingPayload>
        }
        aggregate: {
          args: Prisma.NotificationChannelBindingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationChannelBinding>
        }
        groupBy: {
          args: Prisma.NotificationChannelBindingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelBindingGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationChannelBindingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelBindingCountAggregateOutputType> | number
        }
      }
    }
    Chat: {
      payload: Prisma.$ChatPayload<ExtArgs>
      fields: Prisma.ChatFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ChatFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ChatFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        findFirst: {
          args: Prisma.ChatFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ChatFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        findMany: {
          args: Prisma.ChatFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>[]
        }
        create: {
          args: Prisma.ChatCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        createMany: {
          args: Prisma.ChatCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ChatCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>[]
        }
        delete: {
          args: Prisma.ChatDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        update: {
          args: Prisma.ChatUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        deleteMany: {
          args: Prisma.ChatDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ChatUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ChatUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>[]
        }
        upsert: {
          args: Prisma.ChatUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ChatPayload>
        }
        aggregate: {
          args: Prisma.ChatAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateChat>
        }
        groupBy: {
          args: Prisma.ChatGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ChatGroupByOutputType>[]
        }
        count: {
          args: Prisma.ChatCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ChatCountAggregateOutputType> | number
        }
      }
    }
    Command: {
      payload: Prisma.$CommandPayload<ExtArgs>
      fields: Prisma.CommandFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CommandFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CommandFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        findFirst: {
          args: Prisma.CommandFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CommandFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        findMany: {
          args: Prisma.CommandFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>[]
        }
        create: {
          args: Prisma.CommandCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        createMany: {
          args: Prisma.CommandCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CommandCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>[]
        }
        delete: {
          args: Prisma.CommandDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        update: {
          args: Prisma.CommandUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        deleteMany: {
          args: Prisma.CommandDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CommandUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CommandUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>[]
        }
        upsert: {
          args: Prisma.CommandUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommandPayload>
        }
        aggregate: {
          args: Prisma.CommandAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCommand>
        }
        groupBy: {
          args: Prisma.CommandGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommandGroupByOutputType>[]
        }
        count: {
          args: Prisma.CommandCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommandCountAggregateOutputType> | number
        }
      }
    }
    EncryptedContent: {
      payload: Prisma.$EncryptedContentPayload<ExtArgs>
      fields: Prisma.EncryptedContentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EncryptedContentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EncryptedContentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        findFirst: {
          args: Prisma.EncryptedContentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EncryptedContentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        findMany: {
          args: Prisma.EncryptedContentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>[]
        }
        create: {
          args: Prisma.EncryptedContentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        createMany: {
          args: Prisma.EncryptedContentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EncryptedContentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>[]
        }
        delete: {
          args: Prisma.EncryptedContentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        update: {
          args: Prisma.EncryptedContentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        deleteMany: {
          args: Prisma.EncryptedContentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EncryptedContentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EncryptedContentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>[]
        }
        upsert: {
          args: Prisma.EncryptedContentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EncryptedContentPayload>
        }
        aggregate: {
          args: Prisma.EncryptedContentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEncryptedContent>
        }
        groupBy: {
          args: Prisma.EncryptedContentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EncryptedContentGroupByOutputType>[]
        }
        count: {
          args: Prisma.EncryptedContentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EncryptedContentCountAggregateOutputType> | number
        }
      }
    }
    MemoryNote: {
      payload: Prisma.$MemoryNotePayload<ExtArgs>
      fields: Prisma.MemoryNoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MemoryNoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MemoryNoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        findFirst: {
          args: Prisma.MemoryNoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MemoryNoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        findMany: {
          args: Prisma.MemoryNoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>[]
        }
        create: {
          args: Prisma.MemoryNoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        createMany: {
          args: Prisma.MemoryNoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MemoryNoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>[]
        }
        delete: {
          args: Prisma.MemoryNoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        update: {
          args: Prisma.MemoryNoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        deleteMany: {
          args: Prisma.MemoryNoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MemoryNoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MemoryNoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>[]
        }
        upsert: {
          args: Prisma.MemoryNoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MemoryNotePayload>
        }
        aggregate: {
          args: Prisma.MemoryNoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMemoryNote>
        }
        groupBy: {
          args: Prisma.MemoryNoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MemoryNoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.MemoryNoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MemoryNoteCountAggregateOutputType> | number
        }
      }
    }
    NaturalLanguageInteraction: {
      payload: Prisma.$NaturalLanguageInteractionPayload<ExtArgs>
      fields: Prisma.NaturalLanguageInteractionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NaturalLanguageInteractionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NaturalLanguageInteractionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        findFirst: {
          args: Prisma.NaturalLanguageInteractionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NaturalLanguageInteractionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        findMany: {
          args: Prisma.NaturalLanguageInteractionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>[]
        }
        create: {
          args: Prisma.NaturalLanguageInteractionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        createMany: {
          args: Prisma.NaturalLanguageInteractionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NaturalLanguageInteractionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>[]
        }
        delete: {
          args: Prisma.NaturalLanguageInteractionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        update: {
          args: Prisma.NaturalLanguageInteractionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        deleteMany: {
          args: Prisma.NaturalLanguageInteractionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NaturalLanguageInteractionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NaturalLanguageInteractionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>[]
        }
        upsert: {
          args: Prisma.NaturalLanguageInteractionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NaturalLanguageInteractionPayload>
        }
        aggregate: {
          args: Prisma.NaturalLanguageInteractionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNaturalLanguageInteraction>
        }
        groupBy: {
          args: Prisma.NaturalLanguageInteractionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NaturalLanguageInteractionGroupByOutputType>[]
        }
        count: {
          args: Prisma.NaturalLanguageInteractionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NaturalLanguageInteractionCountAggregateOutputType> | number
        }
      }
    }
    NotificationResponse: {
      payload: Prisma.$NotificationResponsePayload<ExtArgs>
      fields: Prisma.NotificationResponseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationResponseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationResponseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        findFirst: {
          args: Prisma.NotificationResponseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationResponseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        findMany: {
          args: Prisma.NotificationResponseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>[]
        }
        create: {
          args: Prisma.NotificationResponseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        createMany: {
          args: Prisma.NotificationResponseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationResponseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>[]
        }
        delete: {
          args: Prisma.NotificationResponseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        update: {
          args: Prisma.NotificationResponseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        deleteMany: {
          args: Prisma.NotificationResponseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationResponseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationResponseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>[]
        }
        upsert: {
          args: Prisma.NotificationResponseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationResponsePayload>
        }
        aggregate: {
          args: Prisma.NotificationResponseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationResponse>
        }
        groupBy: {
          args: Prisma.NotificationResponseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationResponseGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationResponseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationResponseCountAggregateOutputType> | number
        }
      }
    }
    NotificationTopic: {
      payload: Prisma.$NotificationTopicPayload<ExtArgs>
      fields: Prisma.NotificationTopicFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationTopicFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationTopicFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        findFirst: {
          args: Prisma.NotificationTopicFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationTopicFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        findMany: {
          args: Prisma.NotificationTopicFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>[]
        }
        create: {
          args: Prisma.NotificationTopicCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        createMany: {
          args: Prisma.NotificationTopicCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationTopicCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>[]
        }
        delete: {
          args: Prisma.NotificationTopicDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        update: {
          args: Prisma.NotificationTopicUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        deleteMany: {
          args: Prisma.NotificationTopicDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationTopicUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationTopicUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>[]
        }
        upsert: {
          args: Prisma.NotificationTopicUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTopicPayload>
        }
        aggregate: {
          args: Prisma.NotificationTopicAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationTopic>
        }
        groupBy: {
          args: Prisma.NotificationTopicGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTopicGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationTopicCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTopicCountAggregateOutputType> | number
        }
      }
    }
    NotificationTaskGroup: {
      payload: Prisma.$NotificationTaskGroupPayload<ExtArgs>
      fields: Prisma.NotificationTaskGroupFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationTaskGroupFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationTaskGroupFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        findFirst: {
          args: Prisma.NotificationTaskGroupFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationTaskGroupFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        findMany: {
          args: Prisma.NotificationTaskGroupFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>[]
        }
        create: {
          args: Prisma.NotificationTaskGroupCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        createMany: {
          args: Prisma.NotificationTaskGroupCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationTaskGroupCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>[]
        }
        delete: {
          args: Prisma.NotificationTaskGroupDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        update: {
          args: Prisma.NotificationTaskGroupUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        deleteMany: {
          args: Prisma.NotificationTaskGroupDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationTaskGroupUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationTaskGroupUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>[]
        }
        upsert: {
          args: Prisma.NotificationTaskGroupUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskGroupPayload>
        }
        aggregate: {
          args: Prisma.NotificationTaskGroupAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationTaskGroup>
        }
        groupBy: {
          args: Prisma.NotificationTaskGroupGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskGroupGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationTaskGroupCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskGroupCountAggregateOutputType> | number
        }
      }
    }
    NotificationTask: {
      payload: Prisma.$NotificationTaskPayload<ExtArgs>
      fields: Prisma.NotificationTaskFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationTaskFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationTaskFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        findFirst: {
          args: Prisma.NotificationTaskFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationTaskFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        findMany: {
          args: Prisma.NotificationTaskFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>[]
        }
        create: {
          args: Prisma.NotificationTaskCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        createMany: {
          args: Prisma.NotificationTaskCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationTaskCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>[]
        }
        delete: {
          args: Prisma.NotificationTaskDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        update: {
          args: Prisma.NotificationTaskUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        deleteMany: {
          args: Prisma.NotificationTaskDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationTaskUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationTaskUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>[]
        }
        upsert: {
          args: Prisma.NotificationTaskUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPayload>
        }
        aggregate: {
          args: Prisma.NotificationTaskAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationTask>
        }
        groupBy: {
          args: Prisma.NotificationTaskGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationTaskCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskCountAggregateOutputType> | number
        }
      }
    }
    NotificationTaskPlanningPoll: {
      payload: Prisma.$NotificationTaskPlanningPollPayload<ExtArgs>
      fields: Prisma.NotificationTaskPlanningPollFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationTaskPlanningPollFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationTaskPlanningPollFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        findFirst: {
          args: Prisma.NotificationTaskPlanningPollFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationTaskPlanningPollFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        findMany: {
          args: Prisma.NotificationTaskPlanningPollFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>[]
        }
        create: {
          args: Prisma.NotificationTaskPlanningPollCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        createMany: {
          args: Prisma.NotificationTaskPlanningPollCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationTaskPlanningPollCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>[]
        }
        delete: {
          args: Prisma.NotificationTaskPlanningPollDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        update: {
          args: Prisma.NotificationTaskPlanningPollUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        deleteMany: {
          args: Prisma.NotificationTaskPlanningPollDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationTaskPlanningPollUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationTaskPlanningPollUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>[]
        }
        upsert: {
          args: Prisma.NotificationTaskPlanningPollUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollPayload>
        }
        aggregate: {
          args: Prisma.NotificationTaskPlanningPollAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationTaskPlanningPoll>
        }
        groupBy: {
          args: Prisma.NotificationTaskPlanningPollGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskPlanningPollGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationTaskPlanningPollCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskPlanningPollCountAggregateOutputType> | number
        }
      }
    }
    NotificationTaskPlanningPollOption: {
      payload: Prisma.$NotificationTaskPlanningPollOptionPayload<ExtArgs>
      fields: Prisma.NotificationTaskPlanningPollOptionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationTaskPlanningPollOptionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationTaskPlanningPollOptionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        findFirst: {
          args: Prisma.NotificationTaskPlanningPollOptionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationTaskPlanningPollOptionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        findMany: {
          args: Prisma.NotificationTaskPlanningPollOptionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>[]
        }
        create: {
          args: Prisma.NotificationTaskPlanningPollOptionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        createMany: {
          args: Prisma.NotificationTaskPlanningPollOptionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationTaskPlanningPollOptionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>[]
        }
        delete: {
          args: Prisma.NotificationTaskPlanningPollOptionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        update: {
          args: Prisma.NotificationTaskPlanningPollOptionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        deleteMany: {
          args: Prisma.NotificationTaskPlanningPollOptionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationTaskPlanningPollOptionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationTaskPlanningPollOptionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>[]
        }
        upsert: {
          args: Prisma.NotificationTaskPlanningPollOptionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationTaskPlanningPollOptionPayload>
        }
        aggregate: {
          args: Prisma.NotificationTaskPlanningPollOptionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationTaskPlanningPollOption>
        }
        groupBy: {
          args: Prisma.NotificationTaskPlanningPollOptionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskPlanningPollOptionGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationTaskPlanningPollOptionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationTaskPlanningPollOptionCountAggregateOutputType> | number
        }
      }
    }
    Notification: {
      payload: Prisma.$NotificationPayload<ExtArgs>
      fields: Prisma.NotificationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        findFirst: {
          args: Prisma.NotificationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        findMany: {
          args: Prisma.NotificationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>[]
        }
        create: {
          args: Prisma.NotificationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        createMany: {
          args: Prisma.NotificationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>[]
        }
        delete: {
          args: Prisma.NotificationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        update: {
          args: Prisma.NotificationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        deleteMany: {
          args: Prisma.NotificationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>[]
        }
        upsert: {
          args: Prisma.NotificationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationPayload>
        }
        aggregate: {
          args: Prisma.NotificationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotification>
        }
        groupBy: {
          args: Prisma.NotificationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationCountAggregateOutputType> | number
        }
      }
    }
    Operation: {
      payload: Prisma.$OperationPayload<ExtArgs>
      fields: Prisma.OperationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.OperationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.OperationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        findFirst: {
          args: Prisma.OperationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.OperationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        findMany: {
          args: Prisma.OperationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>[]
        }
        create: {
          args: Prisma.OperationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        createMany: {
          args: Prisma.OperationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.OperationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>[]
        }
        delete: {
          args: Prisma.OperationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        update: {
          args: Prisma.OperationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        deleteMany: {
          args: Prisma.OperationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.OperationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.OperationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>[]
        }
        upsert: {
          args: Prisma.OperationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OperationPayload>
        }
        aggregate: {
          args: Prisma.OperationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOperation>
        }
        groupBy: {
          args: Prisma.OperationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OperationGroupByOutputType>[]
        }
        count: {
          args: Prisma.OperationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OperationCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ApprovalRequestScalarFieldEnum = {
  id: 'id',
  operationId: 'operationId',
  title: 'title',
  content: 'content',
  result: 'result',
  resolution: 'resolution',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  respondedAt: 'respondedAt'
} as const

export type ApprovalRequestScalarFieldEnum = (typeof ApprovalRequestScalarFieldEnum)[keyof typeof ApprovalRequestScalarFieldEnum]


export const AvatarScalarFieldEnum = {
  id: 'id',
  subjectId: 'subjectId',
  replicaName: 'replicaName',
  replicaTitle: 'replicaTitle',
  managedBotId: 'managedBotId',
  managedBotUsername: 'managedBotUsername',
  createdByUserId: 'createdByUserId',
  tokenEcid: 'tokenEcid',
  configVersion: 'configVersion',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AvatarScalarFieldEnum = (typeof AvatarScalarFieldEnum)[keyof typeof AvatarScalarFieldEnum]


export const AvatarProvisionRequestScalarFieldEnum = {
  id: 'id',
  operationId: 'operationId',
  subjectId: 'subjectId',
  replicaName: 'replicaName',
  replicaTitle: 'replicaTitle',
  expectedPrefix: 'expectedPrefix',
  createdByUserId: 'createdByUserId',
  notificationId: 'notificationId',
  avatarId: 'avatarId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AvatarProvisionRequestScalarFieldEnum = (typeof AvatarProvisionRequestScalarFieldEnum)[keyof typeof AvatarProvisionRequestScalarFieldEnum]


export const UnauthorizedAvatarScalarFieldEnum = {
  id: 'id',
  managedBotId: 'managedBotId',
  managedBotUsername: 'managedBotUsername',
  createdByUserId: 'createdByUserId',
  reason: 'reason',
  createdAt: 'createdAt'
} as const

export type UnauthorizedAvatarScalarFieldEnum = (typeof UnauthorizedAvatarScalarFieldEnum)[keyof typeof UnauthorizedAvatarScalarFieldEnum]


export const NotificationChannelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  title: 'title',
  description: 'description',
  ownerReplicaName: 'ownerReplicaName'
} as const

export type NotificationChannelScalarFieldEnum = (typeof NotificationChannelScalarFieldEnum)[keyof typeof NotificationChannelScalarFieldEnum]


export const NotificationChannelBindingScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  chatId: 'chatId',
  topicId: 'topicId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationChannelBindingScalarFieldEnum = (typeof NotificationChannelBindingScalarFieldEnum)[keyof typeof NotificationChannelBindingScalarFieldEnum]


export const ChatScalarFieldEnum = {
  id: 'id',
  telegramRhid: 'telegramRhid',
  dataEcid: 'dataEcid',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatScalarFieldEnum = (typeof ChatScalarFieldEnum)[keyof typeof ChatScalarFieldEnum]


export const CommandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  title: 'title',
  description: 'description',
  parameters: 'parameters',
  isProtected: 'isProtected',
  ownerReplicaName: 'ownerReplicaName',
  callbackEndpoint: 'callbackEndpoint',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommandScalarFieldEnum = (typeof CommandScalarFieldEnum)[keyof typeof CommandScalarFieldEnum]


export const EncryptedContentScalarFieldEnum = {
  ecid: 'ecid',
  data: 'data'
} as const

export type EncryptedContentScalarFieldEnum = (typeof EncryptedContentScalarFieldEnum)[keyof typeof EncryptedContentScalarFieldEnum]


export const MemoryNoteScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  content: 'content',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MemoryNoteScalarFieldEnum = (typeof MemoryNoteScalarFieldEnum)[keyof typeof MemoryNoteScalarFieldEnum]


export const NaturalLanguageInteractionScalarFieldEnum = {
  id: 'id',
  chatId: 'chatId',
  userId: 'userId',
  threadRhid: 'threadRhid',
  replicaName: 'replicaName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NaturalLanguageInteractionScalarFieldEnum = (typeof NaturalLanguageInteractionScalarFieldEnum)[keyof typeof NaturalLanguageInteractionScalarFieldEnum]


export const NotificationResponseScalarFieldEnum = {
  operationId: 'operationId',
  type: 'type',
  actionName: 'actionName',
  textResponseEcid: 'textResponseEcid',
  createdAt: 'createdAt'
} as const

export type NotificationResponseScalarFieldEnum = (typeof NotificationResponseScalarFieldEnum)[keyof typeof NotificationResponseScalarFieldEnum]


export const NotificationTopicScalarFieldEnum = {
  id: 'id',
  chatId: 'chatId',
  channelId: 'channelId',
  threadRhid: 'threadRhid',
  threadEcid: 'threadEcid',
  creatorSubjectId: 'creatorSubjectId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationTopicScalarFieldEnum = (typeof NotificationTopicScalarFieldEnum)[keyof typeof NotificationTopicScalarFieldEnum]


export const NotificationTaskGroupScalarFieldEnum = {
  notificationId: 'notificationId',
  stableId: 'stableId',
  title: 'title',
  position: 'position'
} as const

export type NotificationTaskGroupScalarFieldEnum = (typeof NotificationTaskGroupScalarFieldEnum)[keyof typeof NotificationTaskGroupScalarFieldEnum]


export const NotificationTaskScalarFieldEnum = {
  notificationId: 'notificationId',
  groupStableId: 'groupStableId',
  stableId: 'stableId',
  title: 'title',
  status: 'status',
  position: 'position'
} as const

export type NotificationTaskScalarFieldEnum = (typeof NotificationTaskScalarFieldEnum)[keyof typeof NotificationTaskScalarFieldEnum]


export const NotificationTaskPlanningPollScalarFieldEnum = {
  id: 'id',
  notificationId: 'notificationId',
  pollRhid: 'pollRhid',
  messageEcid: 'messageEcid',
  launchedByUserId: 'launchedByUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationTaskPlanningPollScalarFieldEnum = (typeof NotificationTaskPlanningPollScalarFieldEnum)[keyof typeof NotificationTaskPlanningPollScalarFieldEnum]


export const NotificationTaskPlanningPollOptionScalarFieldEnum = {
  pollId: 'pollId',
  optionId: 'optionId',
  taskNotificationId: 'taskNotificationId',
  taskGroupStableId: 'taskGroupStableId',
  taskStableId: 'taskStableId'
} as const

export type NotificationTaskPlanningPollOptionScalarFieldEnum = (typeof NotificationTaskPlanningPollOptionScalarFieldEnum)[keyof typeof NotificationTaskPlanningPollOptionScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  operationId: 'operationId',
  chatId: 'chatId',
  channelId: 'channelId',
  topicId: 'topicId',
  messageRhid: 'messageRhid',
  messageEcid: 'messageEcid',
  callingSubjectId: 'callingSubjectId',
  sendAsSubjectId: 'sendAsSubjectId',
  title: 'title',
  content: 'content',
  status: 'status',
  actionRows: 'actionRows',
  requiresTextResponse: 'requiresTextResponse',
  isProtected: 'isProtected',
  expectImmediateFeedback: 'expectImmediateFeedback',
  acquireTopic: 'acquireTopic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const OperationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  failureReason: 'failureReason',
  failureMessage: 'failureMessage',
  callbackEndpoint: 'callbackEndpoint',
  customData: 'customData',
  reaperActionId: 'reaperActionId',
  type: 'type',
  notificationResponseContextToken: 'notificationResponseContextToken',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resolvedAt: 'resolvedAt'
} as const

export type OperationScalarFieldEnum = (typeof OperationScalarFieldEnum)[keyof typeof OperationScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  telegramRhid: 'telegramRhid',
  telegramUserIdEcid: 'telegramUserIdEcid',
  usernameEcid: 'usernameEcid',
  firstNameEcid: 'firstNameEcid',
  lastNameEcid: 'lastNameEcid',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'ApprovalResult'
 */
export type EnumApprovalResultFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ApprovalResult'>
    


/**
 * Reference to a field of type 'ApprovalResult[]'
 */
export type ListEnumApprovalResultFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ApprovalResult[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'NotificationResponseType'
 */
export type EnumNotificationResponseTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationResponseType'>
    


/**
 * Reference to a field of type 'NotificationResponseType[]'
 */
export type ListEnumNotificationResponseTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationResponseType[]'>
    


/**
 * Reference to a field of type 'NotificationTaskStatus'
 */
export type EnumNotificationTaskStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationTaskStatus'>
    


/**
 * Reference to a field of type 'NotificationTaskStatus[]'
 */
export type ListEnumNotificationTaskStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationTaskStatus[]'>
    


/**
 * Reference to a field of type 'NotificationStatus'
 */
export type EnumNotificationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationStatus'>
    


/**
 * Reference to a field of type 'NotificationStatus[]'
 */
export type ListEnumNotificationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NotificationStatus[]'>
    


/**
 * Reference to a field of type 'OperationStatus'
 */
export type EnumOperationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OperationStatus'>
    


/**
 * Reference to a field of type 'OperationStatus[]'
 */
export type ListEnumOperationStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OperationStatus[]'>
    


/**
 * Reference to a field of type 'OperationType'
 */
export type EnumOperationTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OperationType'>
    


/**
 * Reference to a field of type 'OperationType[]'
 */
export type ListEnumOperationTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'OperationType[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  approvalRequest?: Prisma.ApprovalRequestOmit
  avatar?: Prisma.AvatarOmit
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestOmit
  unauthorizedAvatar?: Prisma.UnauthorizedAvatarOmit
  notificationChannel?: Prisma.NotificationChannelOmit
  notificationChannelBinding?: Prisma.NotificationChannelBindingOmit
  chat?: Prisma.ChatOmit
  command?: Prisma.CommandOmit
  encryptedContent?: Prisma.EncryptedContentOmit
  memoryNote?: Prisma.MemoryNoteOmit
  naturalLanguageInteraction?: Prisma.NaturalLanguageInteractionOmit
  notificationResponse?: Prisma.NotificationResponseOmit
  notificationTopic?: Prisma.NotificationTopicOmit
  notificationTaskGroup?: Prisma.NotificationTaskGroupOmit
  notificationTask?: Prisma.NotificationTaskOmit
  notificationTaskPlanningPoll?: Prisma.NotificationTaskPlanningPollOmit
  notificationTaskPlanningPollOption?: Prisma.NotificationTaskPlanningPollOptionOmit
  notification?: Prisma.NotificationOmit
  operation?: Prisma.OperationOmit
  user?: Prisma.UserOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

