
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Approvers
 * const approvers = await prisma.approver.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Approver
 * Represents an approval handler used to review permission request sets.
 */
export type Approver = Prisma.ApproverModel
/**
 * Model PermissionBinding
 * Represents a permission granted to a subject, optionally scoped to a scope descriptor.
 */
export type PermissionBinding = Prisma.PermissionBindingModel
/**
 * Model PermissionRestriction
 * Represents an explicit restriction preventing a subject from having a permission.
 */
export type PermissionRestriction = Prisma.PermissionRestrictionModel
/**
 * Model EncryptedContent
 * 
 */
export type EncryptedContent = Prisma.EncryptedContentModel
/**
 * Model MemoryNote
 * 
 */
export type MemoryNote = Prisma.MemoryNoteModel
/**
 * Model Operation
 * Represents a long-running operation in the access replica.
 */
export type Operation = Prisma.OperationModel
/**
 * Model PermissionSet
 * Represents a managed permission set for a subject.
 */
export type PermissionSet = Prisma.PermissionSetModel
/**
 * Model PermissionSetItem
 * Represents a permission currently observed in a managed permission set.
 */
export type PermissionSetItem = Prisma.PermissionSetItemModel
/**
 * Model Permission
 * Represents a permission definition that can be granted to subjects.
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Realm
 * Represents a logical grouping of subjects.
 */
export type Realm = Prisma.RealmModel
/**
 * Model PermissionRequestSet
 * Represents a request set for one or more permissions.
 */
export type PermissionRequestSet = Prisma.PermissionRequestSetModel
/**
 * Model PermissionRequestSetItem
 * Represents a requested permission item inside a permission request set.
 */
export type PermissionRequestSetItem = Prisma.PermissionRequestSetItemModel
