
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Notification` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Notification
 * Represents a sent notification tracked by the replica.
 */
export type NotificationModel = runtime.Types.Result.DefaultSelection<Prisma.$NotificationPayload>

export type AggregateNotification = {
  _count: NotificationCountAggregateOutputType | null
  _avg: NotificationAvgAggregateOutputType | null
  _sum: NotificationSumAggregateOutputType | null
  _min: NotificationMinAggregateOutputType | null
  _max: NotificationMaxAggregateOutputType | null
}

export type NotificationAvgAggregateOutputType = {
  id: number | null
  operationId: number | null
  replyToMessageId: number | null
  channelId: number | null
  messageId: number | null
}

export type NotificationSumAggregateOutputType = {
  id: number | null
  operationId: number | null
  replyToMessageId: number | null
  channelId: number | null
  messageId: number | null
}

export type NotificationMinAggregateOutputType = {
  id: number | null
  operationId: number | null
  targetChatId: string | null
  replyToMessageId: number | null
  channelId: number | null
  messageId: number | null
  callingSubjectId: string | null
  sendAsSubjectId: string | null
  title: string | null
  content: string | null
  requiresTextResponse: boolean | null
  isProtected: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotificationMaxAggregateOutputType = {
  id: number | null
  operationId: number | null
  targetChatId: string | null
  replyToMessageId: number | null
  channelId: number | null
  messageId: number | null
  callingSubjectId: string | null
  sendAsSubjectId: string | null
  title: string | null
  content: string | null
  requiresTextResponse: boolean | null
  isProtected: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NotificationCountAggregateOutputType = {
  id: number
  operationId: number
  targetChatId: number
  replyToMessageId: number
  channelId: number
  messageId: number
  callingSubjectId: number
  sendAsSubjectId: number
  title: number
  content: number
  allowedActions: number
  requiresTextResponse: number
  isProtected: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NotificationAvgAggregateInputType = {
  id?: true
  operationId?: true
  replyToMessageId?: true
  channelId?: true
  messageId?: true
}

export type NotificationSumAggregateInputType = {
  id?: true
  operationId?: true
  replyToMessageId?: true
  channelId?: true
  messageId?: true
}

export type NotificationMinAggregateInputType = {
  id?: true
  operationId?: true
  targetChatId?: true
  replyToMessageId?: true
  channelId?: true
  messageId?: true
  callingSubjectId?: true
  sendAsSubjectId?: true
  title?: true
  content?: true
  requiresTextResponse?: true
  isProtected?: true
  createdAt?: true
  updatedAt?: true
}

export type NotificationMaxAggregateInputType = {
  id?: true
  operationId?: true
  targetChatId?: true
  replyToMessageId?: true
  channelId?: true
  messageId?: true
  callingSubjectId?: true
  sendAsSubjectId?: true
  title?: true
  content?: true
  requiresTextResponse?: true
  isProtected?: true
  createdAt?: true
  updatedAt?: true
}

export type NotificationCountAggregateInputType = {
  id?: true
  operationId?: true
  targetChatId?: true
  replyToMessageId?: true
  channelId?: true
  messageId?: true
  callingSubjectId?: true
  sendAsSubjectId?: true
  title?: true
  content?: true
  allowedActions?: true
  requiresTextResponse?: true
  isProtected?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NotificationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notification to aggregate.
   */
  where?: Prisma.NotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Notifications
  **/
  _count?: true | NotificationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NotificationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NotificationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotificationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotificationMaxAggregateInputType
}

export type GetNotificationAggregateType<T extends NotificationAggregateArgs> = {
      [P in keyof T & keyof AggregateNotification]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotification[P]>
    : Prisma.GetScalarType<T[P], AggregateNotification[P]>
}




export type NotificationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationWhereInput
  orderBy?: Prisma.NotificationOrderByWithAggregationInput | Prisma.NotificationOrderByWithAggregationInput[]
  by: Prisma.NotificationScalarFieldEnum[] | Prisma.NotificationScalarFieldEnum
  having?: Prisma.NotificationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotificationCountAggregateInputType | true
  _avg?: NotificationAvgAggregateInputType
  _sum?: NotificationSumAggregateInputType
  _min?: NotificationMinAggregateInputType
  _max?: NotificationMaxAggregateInputType
}

export type NotificationGroupByOutputType = {
  id: number
  operationId: number | null
  targetChatId: string
  replyToMessageId: number | null
  channelId: number
  messageId: number
  callingSubjectId: string | null
  sendAsSubjectId: string | null
  title: string
  content: string
  allowedActions: string[]
  requiresTextResponse: boolean
  isProtected: boolean
  createdAt: Date
  updatedAt: Date
  _count: NotificationCountAggregateOutputType | null
  _avg: NotificationAvgAggregateOutputType | null
  _sum: NotificationSumAggregateOutputType | null
  _min: NotificationMinAggregateOutputType | null
  _max: NotificationMaxAggregateOutputType | null
}

type GetNotificationGroupByPayload<T extends NotificationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotificationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotificationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotificationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotificationGroupByOutputType[P]>
      }
    >
  >



export type NotificationWhereInput = {
  AND?: Prisma.NotificationWhereInput | Prisma.NotificationWhereInput[]
  OR?: Prisma.NotificationWhereInput[]
  NOT?: Prisma.NotificationWhereInput | Prisma.NotificationWhereInput[]
  id?: Prisma.IntFilter<"Notification"> | number
  operationId?: Prisma.IntNullableFilter<"Notification"> | number | null
  targetChatId?: Prisma.StringFilter<"Notification"> | string
  replyToMessageId?: Prisma.IntNullableFilter<"Notification"> | number | null
  channelId?: Prisma.IntFilter<"Notification"> | number
  messageId?: Prisma.IntFilter<"Notification"> | number
  callingSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  sendAsSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  title?: Prisma.StringFilter<"Notification"> | string
  content?: Prisma.StringFilter<"Notification"> | string
  allowedActions?: Prisma.StringNullableListFilter<"Notification">
  requiresTextResponse?: Prisma.BoolFilter<"Notification"> | boolean
  isProtected?: Prisma.BoolFilter<"Notification"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
  operation?: Prisma.XOR<Prisma.OperationNullableScalarRelationFilter, Prisma.OperationWhereInput> | null
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  channel?: Prisma.XOR<Prisma.NotificationChannelScalarRelationFilter, Prisma.NotificationChannelWhereInput>
  avatarProvisionRequest?: Prisma.XOR<Prisma.AvatarProvisionRequestNullableScalarRelationFilter, Prisma.AvatarProvisionRequestWhereInput> | null
}

export type NotificationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrderInput | Prisma.SortOrder
  targetChatId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  callingSubjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  sendAsSubjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  allowedActions?: Prisma.SortOrder
  requiresTextResponse?: Prisma.SortOrder
  isProtected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  operation?: Prisma.OperationOrderByWithRelationInput
  chat?: Prisma.ChatOrderByWithRelationInput
  channel?: Prisma.NotificationChannelOrderByWithRelationInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestOrderByWithRelationInput
}

export type NotificationWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  operationId?: number
  AND?: Prisma.NotificationWhereInput | Prisma.NotificationWhereInput[]
  OR?: Prisma.NotificationWhereInput[]
  NOT?: Prisma.NotificationWhereInput | Prisma.NotificationWhereInput[]
  targetChatId?: Prisma.StringFilter<"Notification"> | string
  replyToMessageId?: Prisma.IntNullableFilter<"Notification"> | number | null
  channelId?: Prisma.IntFilter<"Notification"> | number
  messageId?: Prisma.IntFilter<"Notification"> | number
  callingSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  sendAsSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  title?: Prisma.StringFilter<"Notification"> | string
  content?: Prisma.StringFilter<"Notification"> | string
  allowedActions?: Prisma.StringNullableListFilter<"Notification">
  requiresTextResponse?: Prisma.BoolFilter<"Notification"> | boolean
  isProtected?: Prisma.BoolFilter<"Notification"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
  operation?: Prisma.XOR<Prisma.OperationNullableScalarRelationFilter, Prisma.OperationWhereInput> | null
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  channel?: Prisma.XOR<Prisma.NotificationChannelScalarRelationFilter, Prisma.NotificationChannelWhereInput>
  avatarProvisionRequest?: Prisma.XOR<Prisma.AvatarProvisionRequestNullableScalarRelationFilter, Prisma.AvatarProvisionRequestWhereInput> | null
}, "id" | "operationId">

export type NotificationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrderInput | Prisma.SortOrder
  targetChatId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  callingSubjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  sendAsSubjectId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  allowedActions?: Prisma.SortOrder
  requiresTextResponse?: Prisma.SortOrder
  isProtected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NotificationCountOrderByAggregateInput
  _avg?: Prisma.NotificationAvgOrderByAggregateInput
  _max?: Prisma.NotificationMaxOrderByAggregateInput
  _min?: Prisma.NotificationMinOrderByAggregateInput
  _sum?: Prisma.NotificationSumOrderByAggregateInput
}

export type NotificationScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotificationScalarWhereWithAggregatesInput | Prisma.NotificationScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotificationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotificationScalarWhereWithAggregatesInput | Prisma.NotificationScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Notification"> | number
  operationId?: Prisma.IntNullableWithAggregatesFilter<"Notification"> | number | null
  targetChatId?: Prisma.StringWithAggregatesFilter<"Notification"> | string
  replyToMessageId?: Prisma.IntNullableWithAggregatesFilter<"Notification"> | number | null
  channelId?: Prisma.IntWithAggregatesFilter<"Notification"> | number
  messageId?: Prisma.IntWithAggregatesFilter<"Notification"> | number
  callingSubjectId?: Prisma.StringNullableWithAggregatesFilter<"Notification"> | string | null
  sendAsSubjectId?: Prisma.StringNullableWithAggregatesFilter<"Notification"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"Notification"> | string
  content?: Prisma.StringWithAggregatesFilter<"Notification"> | string
  allowedActions?: Prisma.StringNullableListFilter<"Notification">
  requiresTextResponse?: Prisma.BoolWithAggregatesFilter<"Notification"> | boolean
  isProtected?: Prisma.BoolWithAggregatesFilter<"Notification"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Notification"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Notification"> | Date | string
}

export type NotificationCreateInput = {
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  operation?: Prisma.OperationCreateNestedOneWithoutNotificationInput
  chat: Prisma.ChatCreateNestedOneWithoutNotificationsInput
  channel: Prisma.NotificationChannelCreateNestedOneWithoutNotificationsInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestCreateNestedOneWithoutNotificationInput
}

export type NotificationUncheckedCreateInput = {
  id?: number
  operationId?: number | null
  targetChatId: string
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedCreateNestedOneWithoutNotificationInput
}

export type NotificationUpdateInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operation?: Prisma.OperationUpdateOneWithoutNotificationNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutNotificationsNestedInput
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutNotificationsNestedInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedUpdateOneWithoutNotificationNestedInput
}

export type NotificationCreateManyInput = {
  id?: number
  operationId?: number | null
  targetChatId: string
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationUpdateManyMutationInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationNullableScalarRelationFilter = {
  is?: Prisma.NotificationWhereInput | null
  isNot?: Prisma.NotificationWhereInput | null
}

export type NotificationListRelationFilter = {
  every?: Prisma.NotificationWhereInput
  some?: Prisma.NotificationWhereInput
  none?: Prisma.NotificationWhereInput
}

export type NotificationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type NotificationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  targetChatId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  callingSubjectId?: Prisma.SortOrder
  sendAsSubjectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  allowedActions?: Prisma.SortOrder
  requiresTextResponse?: Prisma.SortOrder
  isProtected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
}

export type NotificationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  targetChatId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  callingSubjectId?: Prisma.SortOrder
  sendAsSubjectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  requiresTextResponse?: Prisma.SortOrder
  isProtected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  targetChatId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  callingSubjectId?: Prisma.SortOrder
  sendAsSubjectId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  requiresTextResponse?: Prisma.SortOrder
  isProtected?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NotificationSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  replyToMessageId?: Prisma.SortOrder
  channelId?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
}

export type NotificationCreateNestedOneWithoutAvatarProvisionRequestInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedCreateWithoutAvatarProvisionRequestInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutAvatarProvisionRequestInput
  connect?: Prisma.NotificationWhereUniqueInput
}

export type NotificationUpdateOneWithoutAvatarProvisionRequestNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedCreateWithoutAvatarProvisionRequestInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutAvatarProvisionRequestInput
  upsert?: Prisma.NotificationUpsertWithoutAvatarProvisionRequestInput
  disconnect?: Prisma.NotificationWhereInput | boolean
  delete?: Prisma.NotificationWhereInput | boolean
  connect?: Prisma.NotificationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NotificationUpdateToOneWithWhereWithoutAvatarProvisionRequestInput, Prisma.NotificationUpdateWithoutAvatarProvisionRequestInput>, Prisma.NotificationUncheckedUpdateWithoutAvatarProvisionRequestInput>
}

export type NotificationCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput> | Prisma.NotificationCreateWithoutChannelInput[] | Prisma.NotificationUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChannelInput | Prisma.NotificationCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.NotificationCreateManyChannelInputEnvelope
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
}

export type NotificationUncheckedCreateNestedManyWithoutChannelInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput> | Prisma.NotificationCreateWithoutChannelInput[] | Prisma.NotificationUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChannelInput | Prisma.NotificationCreateOrConnectWithoutChannelInput[]
  createMany?: Prisma.NotificationCreateManyChannelInputEnvelope
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
}

export type NotificationUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput> | Prisma.NotificationCreateWithoutChannelInput[] | Prisma.NotificationUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChannelInput | Prisma.NotificationCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.NotificationUpsertWithWhereUniqueWithoutChannelInput | Prisma.NotificationUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.NotificationCreateManyChannelInputEnvelope
  set?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  disconnect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  delete?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  update?: Prisma.NotificationUpdateWithWhereUniqueWithoutChannelInput | Prisma.NotificationUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.NotificationUpdateManyWithWhereWithoutChannelInput | Prisma.NotificationUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
}

export type NotificationUncheckedUpdateManyWithoutChannelNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput> | Prisma.NotificationCreateWithoutChannelInput[] | Prisma.NotificationUncheckedCreateWithoutChannelInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChannelInput | Prisma.NotificationCreateOrConnectWithoutChannelInput[]
  upsert?: Prisma.NotificationUpsertWithWhereUniqueWithoutChannelInput | Prisma.NotificationUpsertWithWhereUniqueWithoutChannelInput[]
  createMany?: Prisma.NotificationCreateManyChannelInputEnvelope
  set?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  disconnect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  delete?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  update?: Prisma.NotificationUpdateWithWhereUniqueWithoutChannelInput | Prisma.NotificationUpdateWithWhereUniqueWithoutChannelInput[]
  updateMany?: Prisma.NotificationUpdateManyWithWhereWithoutChannelInput | Prisma.NotificationUpdateManyWithWhereWithoutChannelInput[]
  deleteMany?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
}

export type NotificationCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput> | Prisma.NotificationCreateWithoutChatInput[] | Prisma.NotificationUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChatInput | Prisma.NotificationCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.NotificationCreateManyChatInputEnvelope
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
}

export type NotificationUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput> | Prisma.NotificationCreateWithoutChatInput[] | Prisma.NotificationUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChatInput | Prisma.NotificationCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.NotificationCreateManyChatInputEnvelope
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
}

export type NotificationUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput> | Prisma.NotificationCreateWithoutChatInput[] | Prisma.NotificationUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChatInput | Prisma.NotificationCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.NotificationUpsertWithWhereUniqueWithoutChatInput | Prisma.NotificationUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.NotificationCreateManyChatInputEnvelope
  set?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  disconnect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  delete?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  update?: Prisma.NotificationUpdateWithWhereUniqueWithoutChatInput | Prisma.NotificationUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.NotificationUpdateManyWithWhereWithoutChatInput | Prisma.NotificationUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
}

export type NotificationUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput> | Prisma.NotificationCreateWithoutChatInput[] | Prisma.NotificationUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutChatInput | Prisma.NotificationCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.NotificationUpsertWithWhereUniqueWithoutChatInput | Prisma.NotificationUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.NotificationCreateManyChatInputEnvelope
  set?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  disconnect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  delete?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  connect?: Prisma.NotificationWhereUniqueInput | Prisma.NotificationWhereUniqueInput[]
  update?: Prisma.NotificationUpdateWithWhereUniqueWithoutChatInput | Prisma.NotificationUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.NotificationUpdateManyWithWhereWithoutChatInput | Prisma.NotificationUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
}

export type NotificationCreateallowedActionsInput = {
  set: string[]
}

export type NotificationUpdateallowedActionsInput = {
  set?: string[]
  push?: string | string[]
}

export type NotificationCreateNestedOneWithoutOperationInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutOperationInput
  connect?: Prisma.NotificationWhereUniqueInput
}

export type NotificationUncheckedCreateNestedOneWithoutOperationInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutOperationInput
  connect?: Prisma.NotificationWhereUniqueInput
}

export type NotificationUpdateOneWithoutOperationNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutOperationInput
  upsert?: Prisma.NotificationUpsertWithoutOperationInput
  disconnect?: Prisma.NotificationWhereInput | boolean
  delete?: Prisma.NotificationWhereInput | boolean
  connect?: Prisma.NotificationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NotificationUpdateToOneWithWhereWithoutOperationInput, Prisma.NotificationUpdateWithoutOperationInput>, Prisma.NotificationUncheckedUpdateWithoutOperationInput>
}

export type NotificationUncheckedUpdateOneWithoutOperationNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
  connectOrCreate?: Prisma.NotificationCreateOrConnectWithoutOperationInput
  upsert?: Prisma.NotificationUpsertWithoutOperationInput
  disconnect?: Prisma.NotificationWhereInput | boolean
  delete?: Prisma.NotificationWhereInput | boolean
  connect?: Prisma.NotificationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NotificationUpdateToOneWithWhereWithoutOperationInput, Prisma.NotificationUpdateWithoutOperationInput>, Prisma.NotificationUncheckedUpdateWithoutOperationInput>
}

export type NotificationCreateWithoutAvatarProvisionRequestInput = {
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  operation?: Prisma.OperationCreateNestedOneWithoutNotificationInput
  chat: Prisma.ChatCreateNestedOneWithoutNotificationsInput
  channel: Prisma.NotificationChannelCreateNestedOneWithoutNotificationsInput
}

export type NotificationUncheckedCreateWithoutAvatarProvisionRequestInput = {
  id?: number
  operationId?: number | null
  targetChatId: string
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationCreateOrConnectWithoutAvatarProvisionRequestInput = {
  where: Prisma.NotificationWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationCreateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedCreateWithoutAvatarProvisionRequestInput>
}

export type NotificationUpsertWithoutAvatarProvisionRequestInput = {
  update: Prisma.XOR<Prisma.NotificationUpdateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedUpdateWithoutAvatarProvisionRequestInput>
  create: Prisma.XOR<Prisma.NotificationCreateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedCreateWithoutAvatarProvisionRequestInput>
  where?: Prisma.NotificationWhereInput
}

export type NotificationUpdateToOneWithWhereWithoutAvatarProvisionRequestInput = {
  where?: Prisma.NotificationWhereInput
  data: Prisma.XOR<Prisma.NotificationUpdateWithoutAvatarProvisionRequestInput, Prisma.NotificationUncheckedUpdateWithoutAvatarProvisionRequestInput>
}

export type NotificationUpdateWithoutAvatarProvisionRequestInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operation?: Prisma.OperationUpdateOneWithoutNotificationNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutNotificationsNestedInput
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutNotificationsNestedInput
}

export type NotificationUncheckedUpdateWithoutAvatarProvisionRequestInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationCreateWithoutChannelInput = {
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  operation?: Prisma.OperationCreateNestedOneWithoutNotificationInput
  chat: Prisma.ChatCreateNestedOneWithoutNotificationsInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestCreateNestedOneWithoutNotificationInput
}

export type NotificationUncheckedCreateWithoutChannelInput = {
  id?: number
  operationId?: number | null
  targetChatId: string
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedCreateNestedOneWithoutNotificationInput
}

export type NotificationCreateOrConnectWithoutChannelInput = {
  where: Prisma.NotificationWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput>
}

export type NotificationCreateManyChannelInputEnvelope = {
  data: Prisma.NotificationCreateManyChannelInput | Prisma.NotificationCreateManyChannelInput[]
  skipDuplicates?: boolean
}

export type NotificationUpsertWithWhereUniqueWithoutChannelInput = {
  where: Prisma.NotificationWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationUpdateWithoutChannelInput, Prisma.NotificationUncheckedUpdateWithoutChannelInput>
  create: Prisma.XOR<Prisma.NotificationCreateWithoutChannelInput, Prisma.NotificationUncheckedCreateWithoutChannelInput>
}

export type NotificationUpdateWithWhereUniqueWithoutChannelInput = {
  where: Prisma.NotificationWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationUpdateWithoutChannelInput, Prisma.NotificationUncheckedUpdateWithoutChannelInput>
}

export type NotificationUpdateManyWithWhereWithoutChannelInput = {
  where: Prisma.NotificationScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationUpdateManyMutationInput, Prisma.NotificationUncheckedUpdateManyWithoutChannelInput>
}

export type NotificationScalarWhereInput = {
  AND?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
  OR?: Prisma.NotificationScalarWhereInput[]
  NOT?: Prisma.NotificationScalarWhereInput | Prisma.NotificationScalarWhereInput[]
  id?: Prisma.IntFilter<"Notification"> | number
  operationId?: Prisma.IntNullableFilter<"Notification"> | number | null
  targetChatId?: Prisma.StringFilter<"Notification"> | string
  replyToMessageId?: Prisma.IntNullableFilter<"Notification"> | number | null
  channelId?: Prisma.IntFilter<"Notification"> | number
  messageId?: Prisma.IntFilter<"Notification"> | number
  callingSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  sendAsSubjectId?: Prisma.StringNullableFilter<"Notification"> | string | null
  title?: Prisma.StringFilter<"Notification"> | string
  content?: Prisma.StringFilter<"Notification"> | string
  allowedActions?: Prisma.StringNullableListFilter<"Notification">
  requiresTextResponse?: Prisma.BoolFilter<"Notification"> | boolean
  isProtected?: Prisma.BoolFilter<"Notification"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Notification"> | Date | string
}

export type NotificationCreateWithoutChatInput = {
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  operation?: Prisma.OperationCreateNestedOneWithoutNotificationInput
  channel: Prisma.NotificationChannelCreateNestedOneWithoutNotificationsInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestCreateNestedOneWithoutNotificationInput
}

export type NotificationUncheckedCreateWithoutChatInput = {
  id?: number
  operationId?: number | null
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedCreateNestedOneWithoutNotificationInput
}

export type NotificationCreateOrConnectWithoutChatInput = {
  where: Prisma.NotificationWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput>
}

export type NotificationCreateManyChatInputEnvelope = {
  data: Prisma.NotificationCreateManyChatInput | Prisma.NotificationCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type NotificationUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.NotificationWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationUpdateWithoutChatInput, Prisma.NotificationUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.NotificationCreateWithoutChatInput, Prisma.NotificationUncheckedCreateWithoutChatInput>
}

export type NotificationUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.NotificationWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationUpdateWithoutChatInput, Prisma.NotificationUncheckedUpdateWithoutChatInput>
}

export type NotificationUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.NotificationScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationUpdateManyMutationInput, Prisma.NotificationUncheckedUpdateManyWithoutChatInput>
}

export type NotificationCreateWithoutOperationInput = {
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutNotificationsInput
  channel: Prisma.NotificationChannelCreateNestedOneWithoutNotificationsInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestCreateNestedOneWithoutNotificationInput
}

export type NotificationUncheckedCreateWithoutOperationInput = {
  id?: number
  targetChatId: string
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedCreateNestedOneWithoutNotificationInput
}

export type NotificationCreateOrConnectWithoutOperationInput = {
  where: Prisma.NotificationWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
}

export type NotificationUpsertWithoutOperationInput = {
  update: Prisma.XOR<Prisma.NotificationUpdateWithoutOperationInput, Prisma.NotificationUncheckedUpdateWithoutOperationInput>
  create: Prisma.XOR<Prisma.NotificationCreateWithoutOperationInput, Prisma.NotificationUncheckedCreateWithoutOperationInput>
  where?: Prisma.NotificationWhereInput
}

export type NotificationUpdateToOneWithWhereWithoutOperationInput = {
  where?: Prisma.NotificationWhereInput
  data: Prisma.XOR<Prisma.NotificationUpdateWithoutOperationInput, Prisma.NotificationUncheckedUpdateWithoutOperationInput>
}

export type NotificationUpdateWithoutOperationInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutNotificationsNestedInput
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutNotificationsNestedInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateWithoutOperationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedUpdateOneWithoutNotificationNestedInput
}

export type NotificationCreateManyChannelInput = {
  id?: number
  operationId?: number | null
  targetChatId: string
  replyToMessageId?: number | null
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationUpdateWithoutChannelInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operation?: Prisma.OperationUpdateOneWithoutNotificationNestedInput
  chat?: Prisma.ChatUpdateOneRequiredWithoutNotificationsNestedInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateWithoutChannelInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateManyWithoutChannelInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  targetChatId?: Prisma.StringFieldUpdateOperationsInput | string
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationCreateManyChatInput = {
  id?: number
  operationId?: number | null
  replyToMessageId?: number | null
  channelId: number
  messageId: number
  callingSubjectId?: string | null
  sendAsSubjectId?: string | null
  title: string
  content: string
  allowedActions?: Prisma.NotificationCreateallowedActionsInput | string[]
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NotificationUpdateWithoutChatInput = {
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operation?: Prisma.OperationUpdateOneWithoutNotificationNestedInput
  channel?: Prisma.NotificationChannelUpdateOneRequiredWithoutNotificationsNestedInput
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateWithoutChatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarProvisionRequest?: Prisma.AvatarProvisionRequestUncheckedUpdateOneWithoutNotificationNestedInput
}

export type NotificationUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  operationId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  replyToMessageId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  channelId?: Prisma.IntFieldUpdateOperationsInput | number
  messageId?: Prisma.IntFieldUpdateOperationsInput | number
  callingSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sendAsSubjectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  allowedActions?: Prisma.NotificationUpdateallowedActionsInput | string[]
  requiresTextResponse?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isProtected?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NotificationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operationId?: boolean
  targetChatId?: boolean
  replyToMessageId?: boolean
  channelId?: boolean
  messageId?: boolean
  callingSubjectId?: boolean
  sendAsSubjectId?: boolean
  title?: boolean
  content?: boolean
  allowedActions?: boolean
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  avatarProvisionRequest?: boolean | Prisma.Notification$avatarProvisionRequestArgs<ExtArgs>
}, ExtArgs["result"]["notification"]>

export type NotificationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operationId?: boolean
  targetChatId?: boolean
  replyToMessageId?: boolean
  channelId?: boolean
  messageId?: boolean
  callingSubjectId?: boolean
  sendAsSubjectId?: boolean
  title?: boolean
  content?: boolean
  allowedActions?: boolean
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["notification"]>

export type NotificationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  operationId?: boolean
  targetChatId?: boolean
  replyToMessageId?: boolean
  channelId?: boolean
  messageId?: boolean
  callingSubjectId?: boolean
  sendAsSubjectId?: boolean
  title?: boolean
  content?: boolean
  allowedActions?: boolean
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["notification"]>

export type NotificationSelectScalar = {
  id?: boolean
  operationId?: boolean
  targetChatId?: boolean
  replyToMessageId?: boolean
  channelId?: boolean
  messageId?: boolean
  callingSubjectId?: boolean
  sendAsSubjectId?: boolean
  title?: boolean
  content?: boolean
  allowedActions?: boolean
  requiresTextResponse?: boolean
  isProtected?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NotificationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "operationId" | "targetChatId" | "replyToMessageId" | "channelId" | "messageId" | "callingSubjectId" | "sendAsSubjectId" | "title" | "content" | "allowedActions" | "requiresTextResponse" | "isProtected" | "createdAt" | "updatedAt", ExtArgs["result"]["notification"]>
export type NotificationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
  avatarProvisionRequest?: boolean | Prisma.Notification$avatarProvisionRequestArgs<ExtArgs>
}
export type NotificationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
}
export type NotificationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operation?: boolean | Prisma.Notification$operationArgs<ExtArgs>
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  channel?: boolean | Prisma.NotificationChannelDefaultArgs<ExtArgs>
}

export type $NotificationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Notification"
  objects: {
    /**
     * The operation associated with this notification payload.
     */
    operation: Prisma.$OperationPayload<ExtArgs> | null
    /**
     * The Telegram chat entity where this notification was sent.
     */
    chat: Prisma.$ChatPayload<ExtArgs>
    /**
     * The notification channel associated with this notification.
     */
    channel: Prisma.$NotificationChannelPayload<ExtArgs>
    /**
     * The avatar provisioning request that references this notification.
     */
    avatarProvisionRequest: Prisma.$AvatarProvisionRequestPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The unique numeric identifier of the notification.
     */
    id: number
    /**
     * The optional operation associated with this notification response tracking.
     */
    operationId: number | null
    /**
     * The Telegram chat identifier where this notification was sent.
     */
    targetChatId: string
    /**
     * Optional Telegram message identifier this notification replies to.
     */
    replyToMessageId: number | null
    /**
     * The ID of the notification channel associated with this operation.
     */
    channelId: number
    /**
     * The message identifier this notification is associated with.
     */
    messageId: number
    /**
     * The subject that called notification sending API.
     */
    callingSubjectId: string | null
    /**
     * The effective subject on behalf of which notification was sent.
     */
    sendAsSubjectId: string | null
    /**
     * The stored title of this notification.
     */
    title: string
    /**
     * The stored content of this notification.
     */
    content: string
    /**
     * The list of allowed action names for this notification.
     */
    allowedActions: string[]
    /**
     * Whether this notification requires text response tracking.
     */
    requiresTextResponse: boolean
    /**
     * Whether interaction with this notification requires permission checks.
     */
    isProtected: boolean
    /**
     * The timestamp when this notification was created.
     */
    createdAt: Date
    /**
     * The timestamp when this notification was last updated.
     */
    updatedAt: Date
  }, ExtArgs["result"]["notification"]>
  composites: {}
}

export type NotificationGetPayload<S extends boolean | null | undefined | NotificationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotificationPayload, S>

export type NotificationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotificationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotificationCountAggregateInputType | true
  }

export interface NotificationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Notification'], meta: { name: 'Notification' } }
  /**
   * Find zero or one Notification that matches the filter.
   * @param {NotificationFindUniqueArgs} args - Arguments to find a Notification
   * @example
   * // Get one Notification
   * const notification = await prisma.notification.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotificationFindUniqueArgs>(args: Prisma.SelectSubset<T, NotificationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Notification that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotificationFindUniqueOrThrowArgs} args - Arguments to find a Notification
   * @example
   * // Get one Notification
   * const notification = await prisma.notification.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotificationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotificationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notification that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationFindFirstArgs} args - Arguments to find a Notification
   * @example
   * // Get one Notification
   * const notification = await prisma.notification.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotificationFindFirstArgs>(args?: Prisma.SelectSubset<T, NotificationFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notification that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationFindFirstOrThrowArgs} args - Arguments to find a Notification
   * @example
   * // Get one Notification
   * const notification = await prisma.notification.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotificationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotificationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Notifications
   * const notifications = await prisma.notification.findMany()
   * 
   * // Get first 10 Notifications
   * const notifications = await prisma.notification.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notificationWithIdOnly = await prisma.notification.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotificationFindManyArgs>(args?: Prisma.SelectSubset<T, NotificationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Notification.
   * @param {NotificationCreateArgs} args - Arguments to create a Notification.
   * @example
   * // Create one Notification
   * const Notification = await prisma.notification.create({
   *   data: {
   *     // ... data to create a Notification
   *   }
   * })
   * 
   */
  create<T extends NotificationCreateArgs>(args: Prisma.SelectSubset<T, NotificationCreateArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Notifications.
   * @param {NotificationCreateManyArgs} args - Arguments to create many Notifications.
   * @example
   * // Create many Notifications
   * const notification = await prisma.notification.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotificationCreateManyArgs>(args?: Prisma.SelectSubset<T, NotificationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Notifications and returns the data saved in the database.
   * @param {NotificationCreateManyAndReturnArgs} args - Arguments to create many Notifications.
   * @example
   * // Create many Notifications
   * const notification = await prisma.notification.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Notifications and only return the `id`
   * const notificationWithIdOnly = await prisma.notification.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotificationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotificationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Notification.
   * @param {NotificationDeleteArgs} args - Arguments to delete one Notification.
   * @example
   * // Delete one Notification
   * const Notification = await prisma.notification.delete({
   *   where: {
   *     // ... filter to delete one Notification
   *   }
   * })
   * 
   */
  delete<T extends NotificationDeleteArgs>(args: Prisma.SelectSubset<T, NotificationDeleteArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Notification.
   * @param {NotificationUpdateArgs} args - Arguments to update one Notification.
   * @example
   * // Update one Notification
   * const notification = await prisma.notification.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotificationUpdateArgs>(args: Prisma.SelectSubset<T, NotificationUpdateArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Notifications.
   * @param {NotificationDeleteManyArgs} args - Arguments to filter Notifications to delete.
   * @example
   * // Delete a few Notifications
   * const { count } = await prisma.notification.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotificationDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotificationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Notifications
   * const notification = await prisma.notification.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotificationUpdateManyArgs>(args: Prisma.SelectSubset<T, NotificationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notifications and returns the data updated in the database.
   * @param {NotificationUpdateManyAndReturnArgs} args - Arguments to update many Notifications.
   * @example
   * // Update many Notifications
   * const notification = await prisma.notification.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Notifications and only return the `id`
   * const notificationWithIdOnly = await prisma.notification.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotificationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotificationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Notification.
   * @param {NotificationUpsertArgs} args - Arguments to update or create a Notification.
   * @example
   * // Update or create a Notification
   * const notification = await prisma.notification.upsert({
   *   create: {
   *     // ... data to create a Notification
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Notification we want to update
   *   }
   * })
   */
  upsert<T extends NotificationUpsertArgs>(args: Prisma.SelectSubset<T, NotificationUpsertArgs<ExtArgs>>): Prisma.Prisma__NotificationClient<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationCountArgs} args - Arguments to filter Notifications to count.
   * @example
   * // Count the number of Notifications
   * const count = await prisma.notification.count({
   *   where: {
   *     // ... the filter for the Notifications we want to count
   *   }
   * })
  **/
  count<T extends NotificationCountArgs>(
    args?: Prisma.Subset<T, NotificationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotificationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Notification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotificationAggregateArgs>(args: Prisma.Subset<T, NotificationAggregateArgs>): Prisma.PrismaPromise<GetNotificationAggregateType<T>>

  /**
   * Group by Notification.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotificationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotificationGroupByArgs['orderBy'] }
      : { orderBy?: NotificationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotificationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotificationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Notification model
 */
readonly fields: NotificationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Notification.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotificationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  operation<T extends Prisma.Notification$operationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Notification$operationArgs<ExtArgs>>): Prisma.Prisma__OperationClient<runtime.Types.Result.GetResult<Prisma.$OperationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  channel<T extends Prisma.NotificationChannelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NotificationChannelDefaultArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  avatarProvisionRequest<T extends Prisma.Notification$avatarProvisionRequestArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Notification$avatarProvisionRequestArgs<ExtArgs>>): Prisma.Prisma__AvatarProvisionRequestClient<runtime.Types.Result.GetResult<Prisma.$AvatarProvisionRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Notification model
 */
export interface NotificationFieldRefs {
  readonly id: Prisma.FieldRef<"Notification", 'Int'>
  readonly operationId: Prisma.FieldRef<"Notification", 'Int'>
  readonly targetChatId: Prisma.FieldRef<"Notification", 'String'>
  readonly replyToMessageId: Prisma.FieldRef<"Notification", 'Int'>
  readonly channelId: Prisma.FieldRef<"Notification", 'Int'>
  readonly messageId: Prisma.FieldRef<"Notification", 'Int'>
  readonly callingSubjectId: Prisma.FieldRef<"Notification", 'String'>
  readonly sendAsSubjectId: Prisma.FieldRef<"Notification", 'String'>
  readonly title: Prisma.FieldRef<"Notification", 'String'>
  readonly content: Prisma.FieldRef<"Notification", 'String'>
  readonly allowedActions: Prisma.FieldRef<"Notification", 'String[]'>
  readonly requiresTextResponse: Prisma.FieldRef<"Notification", 'Boolean'>
  readonly isProtected: Prisma.FieldRef<"Notification", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Notification", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Notification", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Notification findUnique
 */
export type NotificationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter, which Notification to fetch.
   */
  where: Prisma.NotificationWhereUniqueInput
}

/**
 * Notification findUniqueOrThrow
 */
export type NotificationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter, which Notification to fetch.
   */
  where: Prisma.NotificationWhereUniqueInput
}

/**
 * Notification findFirst
 */
export type NotificationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter, which Notification to fetch.
   */
  where?: Prisma.NotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notifications.
   */
  cursor?: Prisma.NotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notifications.
   */
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * Notification findFirstOrThrow
 */
export type NotificationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter, which Notification to fetch.
   */
  where?: Prisma.NotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notifications.
   */
  cursor?: Prisma.NotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notifications.
   */
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * Notification findMany
 */
export type NotificationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where?: Prisma.NotificationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Notifications.
   */
  cursor?: Prisma.NotificationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * Notification create
 */
export type NotificationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * The data needed to create a Notification.
   */
  data: Prisma.XOR<Prisma.NotificationCreateInput, Prisma.NotificationUncheckedCreateInput>
}

/**
 * Notification createMany
 */
export type NotificationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Notifications.
   */
  data: Prisma.NotificationCreateManyInput | Prisma.NotificationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Notification createManyAndReturn
 */
export type NotificationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * The data used to create many Notifications.
   */
  data: Prisma.NotificationCreateManyInput | Prisma.NotificationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Notification update
 */
export type NotificationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * The data needed to update a Notification.
   */
  data: Prisma.XOR<Prisma.NotificationUpdateInput, Prisma.NotificationUncheckedUpdateInput>
  /**
   * Choose, which Notification to update.
   */
  where: Prisma.NotificationWhereUniqueInput
}

/**
 * Notification updateMany
 */
export type NotificationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Notifications.
   */
  data: Prisma.XOR<Prisma.NotificationUpdateManyMutationInput, Prisma.NotificationUncheckedUpdateManyInput>
  /**
   * Filter which Notifications to update
   */
  where?: Prisma.NotificationWhereInput
  /**
   * Limit how many Notifications to update.
   */
  limit?: number
}

/**
 * Notification updateManyAndReturn
 */
export type NotificationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * The data used to update Notifications.
   */
  data: Prisma.XOR<Prisma.NotificationUpdateManyMutationInput, Prisma.NotificationUncheckedUpdateManyInput>
  /**
   * Filter which Notifications to update
   */
  where?: Prisma.NotificationWhereInput
  /**
   * Limit how many Notifications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Notification upsert
 */
export type NotificationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * The filter to search for the Notification to update in case it exists.
   */
  where: Prisma.NotificationWhereUniqueInput
  /**
   * In case the Notification found by the `where` argument doesn't exist, create a new Notification with this data.
   */
  create: Prisma.XOR<Prisma.NotificationCreateInput, Prisma.NotificationUncheckedCreateInput>
  /**
   * In case the Notification was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotificationUpdateInput, Prisma.NotificationUncheckedUpdateInput>
}

/**
 * Notification delete
 */
export type NotificationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  /**
   * Filter which Notification to delete.
   */
  where: Prisma.NotificationWhereUniqueInput
}

/**
 * Notification deleteMany
 */
export type NotificationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notifications to delete
   */
  where?: Prisma.NotificationWhereInput
  /**
   * Limit how many Notifications to delete.
   */
  limit?: number
}

/**
 * Notification.operation
 */
export type Notification$operationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Operation
   */
  select?: Prisma.OperationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Operation
   */
  omit?: Prisma.OperationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OperationInclude<ExtArgs> | null
  where?: Prisma.OperationWhereInput
}

/**
 * Notification.avatarProvisionRequest
 */
export type Notification$avatarProvisionRequestArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AvatarProvisionRequest
   */
  select?: Prisma.AvatarProvisionRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AvatarProvisionRequest
   */
  omit?: Prisma.AvatarProvisionRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AvatarProvisionRequestInclude<ExtArgs> | null
  where?: Prisma.AvatarProvisionRequestWhereInput
}

/**
 * Notification without action
 */
export type NotificationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
}
