
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReplicaEndpointDependencySlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ReplicaEndpointDependencySlot
 * Represents a dependency slot that targets an endpoint.
 */
export type ReplicaEndpointDependencySlotModel = runtime.Types.Result.DefaultSelection<Prisma.$ReplicaEndpointDependencySlotPayload>

export type AggregateReplicaEndpointDependencySlot = {
  _count: ReplicaEndpointDependencySlotCountAggregateOutputType | null
  _avg: ReplicaEndpointDependencySlotAvgAggregateOutputType | null
  _sum: ReplicaEndpointDependencySlotSumAggregateOutputType | null
  _min: ReplicaEndpointDependencySlotMinAggregateOutputType | null
  _max: ReplicaEndpointDependencySlotMaxAggregateOutputType | null
}

export type ReplicaEndpointDependencySlotAvgAggregateOutputType = {
  id: number | null
  replicaId: number | null
}

export type ReplicaEndpointDependencySlotSumAggregateOutputType = {
  id: number | null
  replicaId: number | null
}

export type ReplicaEndpointDependencySlotMinAggregateOutputType = {
  id: number | null
  replicaId: number | null
  name: string | null
  defaultEndpoint: string | null
  currentEndpoint: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ReplicaEndpointDependencySlotMaxAggregateOutputType = {
  id: number | null
  replicaId: number | null
  name: string | null
  defaultEndpoint: string | null
  currentEndpoint: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ReplicaEndpointDependencySlotCountAggregateOutputType = {
  id: number
  replicaId: number
  name: number
  defaultEndpoint: number
  currentEndpoint: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ReplicaEndpointDependencySlotAvgAggregateInputType = {
  id?: true
  replicaId?: true
}

export type ReplicaEndpointDependencySlotSumAggregateInputType = {
  id?: true
  replicaId?: true
}

export type ReplicaEndpointDependencySlotMinAggregateInputType = {
  id?: true
  replicaId?: true
  name?: true
  defaultEndpoint?: true
  currentEndpoint?: true
  createdAt?: true
  updatedAt?: true
}

export type ReplicaEndpointDependencySlotMaxAggregateInputType = {
  id?: true
  replicaId?: true
  name?: true
  defaultEndpoint?: true
  currentEndpoint?: true
  createdAt?: true
  updatedAt?: true
}

export type ReplicaEndpointDependencySlotCountAggregateInputType = {
  id?: true
  replicaId?: true
  name?: true
  defaultEndpoint?: true
  currentEndpoint?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ReplicaEndpointDependencySlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReplicaEndpointDependencySlot to aggregate.
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplicaEndpointDependencySlots to fetch.
   */
  orderBy?: Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput | Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplicaEndpointDependencySlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplicaEndpointDependencySlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReplicaEndpointDependencySlots
  **/
  _count?: true | ReplicaEndpointDependencySlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReplicaEndpointDependencySlotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReplicaEndpointDependencySlotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReplicaEndpointDependencySlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReplicaEndpointDependencySlotMaxAggregateInputType
}

export type GetReplicaEndpointDependencySlotAggregateType<T extends ReplicaEndpointDependencySlotAggregateArgs> = {
      [P in keyof T & keyof AggregateReplicaEndpointDependencySlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReplicaEndpointDependencySlot[P]>
    : Prisma.GetScalarType<T[P], AggregateReplicaEndpointDependencySlot[P]>
}




export type ReplicaEndpointDependencySlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  orderBy?: Prisma.ReplicaEndpointDependencySlotOrderByWithAggregationInput | Prisma.ReplicaEndpointDependencySlotOrderByWithAggregationInput[]
  by: Prisma.ReplicaEndpointDependencySlotScalarFieldEnum[] | Prisma.ReplicaEndpointDependencySlotScalarFieldEnum
  having?: Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReplicaEndpointDependencySlotCountAggregateInputType | true
  _avg?: ReplicaEndpointDependencySlotAvgAggregateInputType
  _sum?: ReplicaEndpointDependencySlotSumAggregateInputType
  _min?: ReplicaEndpointDependencySlotMinAggregateInputType
  _max?: ReplicaEndpointDependencySlotMaxAggregateInputType
}

export type ReplicaEndpointDependencySlotGroupByOutputType = {
  id: number
  replicaId: number
  name: string
  defaultEndpoint: string | null
  currentEndpoint: string | null
  createdAt: Date
  updatedAt: Date
  _count: ReplicaEndpointDependencySlotCountAggregateOutputType | null
  _avg: ReplicaEndpointDependencySlotAvgAggregateOutputType | null
  _sum: ReplicaEndpointDependencySlotSumAggregateOutputType | null
  _min: ReplicaEndpointDependencySlotMinAggregateOutputType | null
  _max: ReplicaEndpointDependencySlotMaxAggregateOutputType | null
}

type GetReplicaEndpointDependencySlotGroupByPayload<T extends ReplicaEndpointDependencySlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReplicaEndpointDependencySlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReplicaEndpointDependencySlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReplicaEndpointDependencySlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReplicaEndpointDependencySlotGroupByOutputType[P]>
      }
    >
  >



export type ReplicaEndpointDependencySlotWhereInput = {
  AND?: Prisma.ReplicaEndpointDependencySlotWhereInput | Prisma.ReplicaEndpointDependencySlotWhereInput[]
  OR?: Prisma.ReplicaEndpointDependencySlotWhereInput[]
  NOT?: Prisma.ReplicaEndpointDependencySlotWhereInput | Prisma.ReplicaEndpointDependencySlotWhereInput[]
  id?: Prisma.IntFilter<"ReplicaEndpointDependencySlot"> | number
  replicaId?: Prisma.IntFilter<"ReplicaEndpointDependencySlot"> | number
  name?: Prisma.StringFilter<"ReplicaEndpointDependencySlot"> | string
  defaultEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  currentEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
  replica?: Prisma.XOR<Prisma.ReplicaScalarRelationFilter, Prisma.ReplicaWhereInput>
}

export type ReplicaEndpointDependencySlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  defaultEndpoint?: Prisma.SortOrderInput | Prisma.SortOrder
  currentEndpoint?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  replica?: Prisma.ReplicaOrderByWithRelationInput
}

export type ReplicaEndpointDependencySlotWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  replicaId_name?: Prisma.ReplicaEndpointDependencySlotReplicaIdNameCompoundUniqueInput
  AND?: Prisma.ReplicaEndpointDependencySlotWhereInput | Prisma.ReplicaEndpointDependencySlotWhereInput[]
  OR?: Prisma.ReplicaEndpointDependencySlotWhereInput[]
  NOT?: Prisma.ReplicaEndpointDependencySlotWhereInput | Prisma.ReplicaEndpointDependencySlotWhereInput[]
  replicaId?: Prisma.IntFilter<"ReplicaEndpointDependencySlot"> | number
  name?: Prisma.StringFilter<"ReplicaEndpointDependencySlot"> | string
  defaultEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  currentEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
  replica?: Prisma.XOR<Prisma.ReplicaScalarRelationFilter, Prisma.ReplicaWhereInput>
}, "id" | "replicaId_name">

export type ReplicaEndpointDependencySlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  defaultEndpoint?: Prisma.SortOrderInput | Prisma.SortOrder
  currentEndpoint?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ReplicaEndpointDependencySlotCountOrderByAggregateInput
  _avg?: Prisma.ReplicaEndpointDependencySlotAvgOrderByAggregateInput
  _max?: Prisma.ReplicaEndpointDependencySlotMaxOrderByAggregateInput
  _min?: Prisma.ReplicaEndpointDependencySlotMinOrderByAggregateInput
  _sum?: Prisma.ReplicaEndpointDependencySlotSumOrderByAggregateInput
}

export type ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput | Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput | Prisma.ReplicaEndpointDependencySlotScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | number
  replicaId?: Prisma.IntWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | number
  name?: Prisma.StringWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | string
  defaultEndpoint?: Prisma.StringNullableWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | string | null
  currentEndpoint?: Prisma.StringNullableWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ReplicaEndpointDependencySlot"> | Date | string
}

export type ReplicaEndpointDependencySlotCreateInput = {
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  replica: Prisma.ReplicaCreateNestedOneWithoutEndpointDependencySlotsInput
}

export type ReplicaEndpointDependencySlotUncheckedCreateInput = {
  id?: number
  replicaId: number
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReplicaEndpointDependencySlotUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  replica?: Prisma.ReplicaUpdateOneRequiredWithoutEndpointDependencySlotsNestedInput
}

export type ReplicaEndpointDependencySlotUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  replicaId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplicaEndpointDependencySlotCreateManyInput = {
  id?: number
  replicaId: number
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReplicaEndpointDependencySlotUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplicaEndpointDependencySlotUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  replicaId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplicaEndpointDependencySlotListRelationFilter = {
  every?: Prisma.ReplicaEndpointDependencySlotWhereInput
  some?: Prisma.ReplicaEndpointDependencySlotWhereInput
  none?: Prisma.ReplicaEndpointDependencySlotWhereInput
}

export type ReplicaEndpointDependencySlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotReplicaIdNameCompoundUniqueInput = {
  replicaId: number
  name: string
}

export type ReplicaEndpointDependencySlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  defaultEndpoint?: Prisma.SortOrder
  currentEndpoint?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  defaultEndpoint?: Prisma.SortOrder
  currentEndpoint?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  defaultEndpoint?: Prisma.SortOrder
  currentEndpoint?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  replicaId?: Prisma.SortOrder
}

export type ReplicaEndpointDependencySlotCreateNestedManyWithoutReplicaInput = {
  create?: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput> | Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput[] | Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput[]
  connectOrCreate?: Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput[]
  createMany?: Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInputEnvelope
  connect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
}

export type ReplicaEndpointDependencySlotUncheckedCreateNestedManyWithoutReplicaInput = {
  create?: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput> | Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput[] | Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput[]
  connectOrCreate?: Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput[]
  createMany?: Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInputEnvelope
  connect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
}

export type ReplicaEndpointDependencySlotUpdateManyWithoutReplicaNestedInput = {
  create?: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput> | Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput[] | Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput[]
  connectOrCreate?: Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput[]
  upsert?: Prisma.ReplicaEndpointDependencySlotUpsertWithWhereUniqueWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpsertWithWhereUniqueWithoutReplicaInput[]
  createMany?: Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInputEnvelope
  set?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  disconnect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  delete?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  connect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  update?: Prisma.ReplicaEndpointDependencySlotUpdateWithWhereUniqueWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpdateWithWhereUniqueWithoutReplicaInput[]
  updateMany?: Prisma.ReplicaEndpointDependencySlotUpdateManyWithWhereWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpdateManyWithWhereWithoutReplicaInput[]
  deleteMany?: Prisma.ReplicaEndpointDependencySlotScalarWhereInput | Prisma.ReplicaEndpointDependencySlotScalarWhereInput[]
}

export type ReplicaEndpointDependencySlotUncheckedUpdateManyWithoutReplicaNestedInput = {
  create?: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput> | Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput[] | Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput[]
  connectOrCreate?: Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput[]
  upsert?: Prisma.ReplicaEndpointDependencySlotUpsertWithWhereUniqueWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpsertWithWhereUniqueWithoutReplicaInput[]
  createMany?: Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInputEnvelope
  set?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  disconnect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  delete?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  connect?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput | Prisma.ReplicaEndpointDependencySlotWhereUniqueInput[]
  update?: Prisma.ReplicaEndpointDependencySlotUpdateWithWhereUniqueWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpdateWithWhereUniqueWithoutReplicaInput[]
  updateMany?: Prisma.ReplicaEndpointDependencySlotUpdateManyWithWhereWithoutReplicaInput | Prisma.ReplicaEndpointDependencySlotUpdateManyWithWhereWithoutReplicaInput[]
  deleteMany?: Prisma.ReplicaEndpointDependencySlotScalarWhereInput | Prisma.ReplicaEndpointDependencySlotScalarWhereInput[]
}

export type ReplicaEndpointDependencySlotCreateWithoutReplicaInput = {
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput = {
  id?: number
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReplicaEndpointDependencySlotCreateOrConnectWithoutReplicaInput = {
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  create: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput>
}

export type ReplicaEndpointDependencySlotCreateManyReplicaInputEnvelope = {
  data: Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInput | Prisma.ReplicaEndpointDependencySlotCreateManyReplicaInput[]
  skipDuplicates?: boolean
}

export type ReplicaEndpointDependencySlotUpsertWithWhereUniqueWithoutReplicaInput = {
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  update: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateWithoutReplicaInput>
  create: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateWithoutReplicaInput>
}

export type ReplicaEndpointDependencySlotUpdateWithWhereUniqueWithoutReplicaInput = {
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateWithoutReplicaInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateWithoutReplicaInput>
}

export type ReplicaEndpointDependencySlotUpdateManyWithWhereWithoutReplicaInput = {
  where: Prisma.ReplicaEndpointDependencySlotScalarWhereInput
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateManyMutationInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateManyWithoutReplicaInput>
}

export type ReplicaEndpointDependencySlotScalarWhereInput = {
  AND?: Prisma.ReplicaEndpointDependencySlotScalarWhereInput | Prisma.ReplicaEndpointDependencySlotScalarWhereInput[]
  OR?: Prisma.ReplicaEndpointDependencySlotScalarWhereInput[]
  NOT?: Prisma.ReplicaEndpointDependencySlotScalarWhereInput | Prisma.ReplicaEndpointDependencySlotScalarWhereInput[]
  id?: Prisma.IntFilter<"ReplicaEndpointDependencySlot"> | number
  replicaId?: Prisma.IntFilter<"ReplicaEndpointDependencySlot"> | number
  name?: Prisma.StringFilter<"ReplicaEndpointDependencySlot"> | string
  defaultEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  currentEndpoint?: Prisma.StringNullableFilter<"ReplicaEndpointDependencySlot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ReplicaEndpointDependencySlot"> | Date | string
}

export type ReplicaEndpointDependencySlotCreateManyReplicaInput = {
  id?: number
  name: string
  defaultEndpoint?: string | null
  currentEndpoint?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ReplicaEndpointDependencySlotUpdateWithoutReplicaInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplicaEndpointDependencySlotUncheckedUpdateWithoutReplicaInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReplicaEndpointDependencySlotUncheckedUpdateManyWithoutReplicaInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  defaultEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentEndpoint?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ReplicaEndpointDependencySlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  replicaId?: boolean
  name?: boolean
  defaultEndpoint?: boolean
  currentEndpoint?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["replicaEndpointDependencySlot"]>

export type ReplicaEndpointDependencySlotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  replicaId?: boolean
  name?: boolean
  defaultEndpoint?: boolean
  currentEndpoint?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["replicaEndpointDependencySlot"]>

export type ReplicaEndpointDependencySlotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  replicaId?: boolean
  name?: boolean
  defaultEndpoint?: boolean
  currentEndpoint?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["replicaEndpointDependencySlot"]>

export type ReplicaEndpointDependencySlotSelectScalar = {
  id?: boolean
  replicaId?: boolean
  name?: boolean
  defaultEndpoint?: boolean
  currentEndpoint?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ReplicaEndpointDependencySlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "replicaId" | "name" | "defaultEndpoint" | "currentEndpoint" | "createdAt" | "updatedAt", ExtArgs["result"]["replicaEndpointDependencySlot"]>
export type ReplicaEndpointDependencySlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}
export type ReplicaEndpointDependencySlotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}
export type ReplicaEndpointDependencySlotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  replica?: boolean | Prisma.ReplicaDefaultArgs<ExtArgs>
}

export type $ReplicaEndpointDependencySlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReplicaEndpointDependencySlot"
  objects: {
    /**
     * The owning replica.
     */
    replica: Prisma.$ReplicaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The unique numeric identifier of the slot.
     */
    id: number
    /**
     * The owning replica identifier.
     */
    replicaId: number
    /**
     * The slot name unique within a replica.
     */
    name: string
    /**
     * The default endpoint initially assigned to this slot.
     */
    defaultEndpoint: string | null
    /**
     * The current endpoint assigned to this slot.
     */
    currentEndpoint: string | null
    /**
     * The timestamp when the slot was created.
     */
    createdAt: Date
    /**
     * The timestamp when the slot was last updated.
     */
    updatedAt: Date
  }, ExtArgs["result"]["replicaEndpointDependencySlot"]>
  composites: {}
}

export type ReplicaEndpointDependencySlotGetPayload<S extends boolean | null | undefined | ReplicaEndpointDependencySlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload, S>

export type ReplicaEndpointDependencySlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReplicaEndpointDependencySlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReplicaEndpointDependencySlotCountAggregateInputType | true
  }

export interface ReplicaEndpointDependencySlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReplicaEndpointDependencySlot'], meta: { name: 'ReplicaEndpointDependencySlot' } }
  /**
   * Find zero or one ReplicaEndpointDependencySlot that matches the filter.
   * @param {ReplicaEndpointDependencySlotFindUniqueArgs} args - Arguments to find a ReplicaEndpointDependencySlot
   * @example
   * // Get one ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReplicaEndpointDependencySlotFindUniqueArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReplicaEndpointDependencySlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReplicaEndpointDependencySlotFindUniqueOrThrowArgs} args - Arguments to find a ReplicaEndpointDependencySlot
   * @example
   * // Get one ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReplicaEndpointDependencySlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReplicaEndpointDependencySlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotFindFirstArgs} args - Arguments to find a ReplicaEndpointDependencySlot
   * @example
   * // Get one ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReplicaEndpointDependencySlotFindFirstArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReplicaEndpointDependencySlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotFindFirstOrThrowArgs} args - Arguments to find a ReplicaEndpointDependencySlot
   * @example
   * // Get one ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReplicaEndpointDependencySlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReplicaEndpointDependencySlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlots = await prisma.replicaEndpointDependencySlot.findMany()
   * 
   * // Get first 10 ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlots = await prisma.replicaEndpointDependencySlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const replicaEndpointDependencySlotWithIdOnly = await prisma.replicaEndpointDependencySlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReplicaEndpointDependencySlotFindManyArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReplicaEndpointDependencySlot.
   * @param {ReplicaEndpointDependencySlotCreateArgs} args - Arguments to create a ReplicaEndpointDependencySlot.
   * @example
   * // Create one ReplicaEndpointDependencySlot
   * const ReplicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.create({
   *   data: {
   *     // ... data to create a ReplicaEndpointDependencySlot
   *   }
   * })
   * 
   */
  create<T extends ReplicaEndpointDependencySlotCreateArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotCreateArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReplicaEndpointDependencySlots.
   * @param {ReplicaEndpointDependencySlotCreateManyArgs} args - Arguments to create many ReplicaEndpointDependencySlots.
   * @example
   * // Create many ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReplicaEndpointDependencySlotCreateManyArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ReplicaEndpointDependencySlots and returns the data saved in the database.
   * @param {ReplicaEndpointDependencySlotCreateManyAndReturnArgs} args - Arguments to create many ReplicaEndpointDependencySlots.
   * @example
   * // Create many ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ReplicaEndpointDependencySlots and only return the `id`
   * const replicaEndpointDependencySlotWithIdOnly = await prisma.replicaEndpointDependencySlot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ReplicaEndpointDependencySlotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ReplicaEndpointDependencySlot.
   * @param {ReplicaEndpointDependencySlotDeleteArgs} args - Arguments to delete one ReplicaEndpointDependencySlot.
   * @example
   * // Delete one ReplicaEndpointDependencySlot
   * const ReplicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.delete({
   *   where: {
   *     // ... filter to delete one ReplicaEndpointDependencySlot
   *   }
   * })
   * 
   */
  delete<T extends ReplicaEndpointDependencySlotDeleteArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotDeleteArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReplicaEndpointDependencySlot.
   * @param {ReplicaEndpointDependencySlotUpdateArgs} args - Arguments to update one ReplicaEndpointDependencySlot.
   * @example
   * // Update one ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReplicaEndpointDependencySlotUpdateArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotUpdateArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReplicaEndpointDependencySlots.
   * @param {ReplicaEndpointDependencySlotDeleteManyArgs} args - Arguments to filter ReplicaEndpointDependencySlots to delete.
   * @example
   * // Delete a few ReplicaEndpointDependencySlots
   * const { count } = await prisma.replicaEndpointDependencySlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReplicaEndpointDependencySlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReplicaEndpointDependencySlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReplicaEndpointDependencySlotUpdateManyArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReplicaEndpointDependencySlots and returns the data updated in the database.
   * @param {ReplicaEndpointDependencySlotUpdateManyAndReturnArgs} args - Arguments to update many ReplicaEndpointDependencySlots.
   * @example
   * // Update many ReplicaEndpointDependencySlots
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ReplicaEndpointDependencySlots and only return the `id`
   * const replicaEndpointDependencySlotWithIdOnly = await prisma.replicaEndpointDependencySlot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ReplicaEndpointDependencySlotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ReplicaEndpointDependencySlot.
   * @param {ReplicaEndpointDependencySlotUpsertArgs} args - Arguments to update or create a ReplicaEndpointDependencySlot.
   * @example
   * // Update or create a ReplicaEndpointDependencySlot
   * const replicaEndpointDependencySlot = await prisma.replicaEndpointDependencySlot.upsert({
   *   create: {
   *     // ... data to create a ReplicaEndpointDependencySlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReplicaEndpointDependencySlot we want to update
   *   }
   * })
   */
  upsert<T extends ReplicaEndpointDependencySlotUpsertArgs>(args: Prisma.SelectSubset<T, ReplicaEndpointDependencySlotUpsertArgs<ExtArgs>>): Prisma.Prisma__ReplicaEndpointDependencySlotClient<runtime.Types.Result.GetResult<Prisma.$ReplicaEndpointDependencySlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReplicaEndpointDependencySlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotCountArgs} args - Arguments to filter ReplicaEndpointDependencySlots to count.
   * @example
   * // Count the number of ReplicaEndpointDependencySlots
   * const count = await prisma.replicaEndpointDependencySlot.count({
   *   where: {
   *     // ... the filter for the ReplicaEndpointDependencySlots we want to count
   *   }
   * })
  **/
  count<T extends ReplicaEndpointDependencySlotCountArgs>(
    args?: Prisma.Subset<T, ReplicaEndpointDependencySlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReplicaEndpointDependencySlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReplicaEndpointDependencySlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReplicaEndpointDependencySlotAggregateArgs>(args: Prisma.Subset<T, ReplicaEndpointDependencySlotAggregateArgs>): Prisma.PrismaPromise<GetReplicaEndpointDependencySlotAggregateType<T>>

  /**
   * Group by ReplicaEndpointDependencySlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReplicaEndpointDependencySlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReplicaEndpointDependencySlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReplicaEndpointDependencySlotGroupByArgs['orderBy'] }
      : { orderBy?: ReplicaEndpointDependencySlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReplicaEndpointDependencySlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReplicaEndpointDependencySlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReplicaEndpointDependencySlot model
 */
readonly fields: ReplicaEndpointDependencySlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReplicaEndpointDependencySlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReplicaEndpointDependencySlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  replica<T extends Prisma.ReplicaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ReplicaDefaultArgs<ExtArgs>>): Prisma.Prisma__ReplicaClient<runtime.Types.Result.GetResult<Prisma.$ReplicaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReplicaEndpointDependencySlot model
 */
export interface ReplicaEndpointDependencySlotFieldRefs {
  readonly id: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'Int'>
  readonly replicaId: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'Int'>
  readonly name: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'String'>
  readonly defaultEndpoint: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'String'>
  readonly currentEndpoint: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'String'>
  readonly createdAt: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ReplicaEndpointDependencySlot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReplicaEndpointDependencySlot findUnique
 */
export type ReplicaEndpointDependencySlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter, which ReplicaEndpointDependencySlot to fetch.
   */
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
}

/**
 * ReplicaEndpointDependencySlot findUniqueOrThrow
 */
export type ReplicaEndpointDependencySlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter, which ReplicaEndpointDependencySlot to fetch.
   */
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
}

/**
 * ReplicaEndpointDependencySlot findFirst
 */
export type ReplicaEndpointDependencySlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter, which ReplicaEndpointDependencySlot to fetch.
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplicaEndpointDependencySlots to fetch.
   */
  orderBy?: Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput | Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReplicaEndpointDependencySlots.
   */
  cursor?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplicaEndpointDependencySlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplicaEndpointDependencySlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReplicaEndpointDependencySlots.
   */
  distinct?: Prisma.ReplicaEndpointDependencySlotScalarFieldEnum | Prisma.ReplicaEndpointDependencySlotScalarFieldEnum[]
}

/**
 * ReplicaEndpointDependencySlot findFirstOrThrow
 */
export type ReplicaEndpointDependencySlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter, which ReplicaEndpointDependencySlot to fetch.
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplicaEndpointDependencySlots to fetch.
   */
  orderBy?: Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput | Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReplicaEndpointDependencySlots.
   */
  cursor?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplicaEndpointDependencySlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplicaEndpointDependencySlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReplicaEndpointDependencySlots.
   */
  distinct?: Prisma.ReplicaEndpointDependencySlotScalarFieldEnum | Prisma.ReplicaEndpointDependencySlotScalarFieldEnum[]
}

/**
 * ReplicaEndpointDependencySlot findMany
 */
export type ReplicaEndpointDependencySlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter, which ReplicaEndpointDependencySlots to fetch.
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReplicaEndpointDependencySlots to fetch.
   */
  orderBy?: Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput | Prisma.ReplicaEndpointDependencySlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReplicaEndpointDependencySlots.
   */
  cursor?: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReplicaEndpointDependencySlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReplicaEndpointDependencySlots.
   */
  skip?: number
  distinct?: Prisma.ReplicaEndpointDependencySlotScalarFieldEnum | Prisma.ReplicaEndpointDependencySlotScalarFieldEnum[]
}

/**
 * ReplicaEndpointDependencySlot create
 */
export type ReplicaEndpointDependencySlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * The data needed to create a ReplicaEndpointDependencySlot.
   */
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateInput>
}

/**
 * ReplicaEndpointDependencySlot createMany
 */
export type ReplicaEndpointDependencySlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReplicaEndpointDependencySlots.
   */
  data: Prisma.ReplicaEndpointDependencySlotCreateManyInput | Prisma.ReplicaEndpointDependencySlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReplicaEndpointDependencySlot createManyAndReturn
 */
export type ReplicaEndpointDependencySlotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * The data used to create many ReplicaEndpointDependencySlots.
   */
  data: Prisma.ReplicaEndpointDependencySlotCreateManyInput | Prisma.ReplicaEndpointDependencySlotCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ReplicaEndpointDependencySlot update
 */
export type ReplicaEndpointDependencySlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * The data needed to update a ReplicaEndpointDependencySlot.
   */
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateInput>
  /**
   * Choose, which ReplicaEndpointDependencySlot to update.
   */
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
}

/**
 * ReplicaEndpointDependencySlot updateMany
 */
export type ReplicaEndpointDependencySlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReplicaEndpointDependencySlots.
   */
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateManyMutationInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateManyInput>
  /**
   * Filter which ReplicaEndpointDependencySlots to update
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * Limit how many ReplicaEndpointDependencySlots to update.
   */
  limit?: number
}

/**
 * ReplicaEndpointDependencySlot updateManyAndReturn
 */
export type ReplicaEndpointDependencySlotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * The data used to update ReplicaEndpointDependencySlots.
   */
  data: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateManyMutationInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateManyInput>
  /**
   * Filter which ReplicaEndpointDependencySlots to update
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * Limit how many ReplicaEndpointDependencySlots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ReplicaEndpointDependencySlot upsert
 */
export type ReplicaEndpointDependencySlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * The filter to search for the ReplicaEndpointDependencySlot to update in case it exists.
   */
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
  /**
   * In case the ReplicaEndpointDependencySlot found by the `where` argument doesn't exist, create a new ReplicaEndpointDependencySlot with this data.
   */
  create: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotCreateInput, Prisma.ReplicaEndpointDependencySlotUncheckedCreateInput>
  /**
   * In case the ReplicaEndpointDependencySlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReplicaEndpointDependencySlotUpdateInput, Prisma.ReplicaEndpointDependencySlotUncheckedUpdateInput>
}

/**
 * ReplicaEndpointDependencySlot delete
 */
export type ReplicaEndpointDependencySlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
  /**
   * Filter which ReplicaEndpointDependencySlot to delete.
   */
  where: Prisma.ReplicaEndpointDependencySlotWhereUniqueInput
}

/**
 * ReplicaEndpointDependencySlot deleteMany
 */
export type ReplicaEndpointDependencySlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReplicaEndpointDependencySlots to delete
   */
  where?: Prisma.ReplicaEndpointDependencySlotWhereInput
  /**
   * Limit how many ReplicaEndpointDependencySlots to delete.
   */
  limit?: number
}

/**
 * ReplicaEndpointDependencySlot without action
 */
export type ReplicaEndpointDependencySlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReplicaEndpointDependencySlot
   */
  select?: Prisma.ReplicaEndpointDependencySlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReplicaEndpointDependencySlot
   */
  omit?: Prisma.ReplicaEndpointDependencySlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReplicaEndpointDependencySlotInclude<ExtArgs> | null
}
