// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: common/subject.v1.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { StringValue } from "../google/protobuf/wrappers";

export const protobufPackage = "reside.common.subject.v1";

/** Display information for a subject. */
export interface SubjectDisplayInfo {
  /** The required human-readable title of the subject. */
  title: string;
  /** The optional avatar URL of the subject. */
  avatarUrl: string | undefined;
}

/** Request to fetch display info for a subject. */
export interface GetSubjectDisplayInfoRequest {
  /** The unique subject identifier in format "{realm}:{name}". */
  subjectId: string;
}

function createBaseSubjectDisplayInfo(): SubjectDisplayInfo {
  return { title: "", avatarUrl: undefined };
}

export const SubjectDisplayInfo: MessageFns<SubjectDisplayInfo> = {
  encode(message: SubjectDisplayInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.avatarUrl !== undefined) {
      StringValue.encode({ value: message.avatarUrl! }, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubjectDisplayInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubjectDisplayInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatarUrl = StringValue.decode(reader, reader.uint32()).value;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubjectDisplayInfo {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      avatarUrl: isSet(object.avatarUrl)
        ? String(object.avatarUrl)
        : isSet(object.avatar_url)
        ? String(object.avatar_url)
        : undefined,
    };
  },

  toJSON(message: SubjectDisplayInfo): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.avatarUrl !== undefined) {
      obj.avatarUrl = message.avatarUrl;
    }
    return obj;
  },

  create(base?: DeepPartial<SubjectDisplayInfo>): SubjectDisplayInfo {
    return SubjectDisplayInfo.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubjectDisplayInfo>): SubjectDisplayInfo {
    const message = createBaseSubjectDisplayInfo();
    message.title = object.title ?? "";
    message.avatarUrl = object.avatarUrl ?? undefined;
    return message;
  },
};

function createBaseGetSubjectDisplayInfoRequest(): GetSubjectDisplayInfoRequest {
  return { subjectId: "" };
}

export const GetSubjectDisplayInfoRequest: MessageFns<GetSubjectDisplayInfoRequest> = {
  encode(message: GetSubjectDisplayInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subjectId !== "") {
      writer.uint32(10).string(message.subjectId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubjectDisplayInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubjectDisplayInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subjectId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSubjectDisplayInfoRequest {
    return {
      subjectId: isSet(object.subjectId)
        ? globalThis.String(object.subjectId)
        : isSet(object.subject_id)
        ? globalThis.String(object.subject_id)
        : "",
    };
  },

  toJSON(message: GetSubjectDisplayInfoRequest): unknown {
    const obj: any = {};
    if (message.subjectId !== "") {
      obj.subjectId = message.subjectId;
    }
    return obj;
  },

  create(base?: DeepPartial<GetSubjectDisplayInfoRequest>): GetSubjectDisplayInfoRequest {
    return GetSubjectDisplayInfoRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSubjectDisplayInfoRequest>): GetSubjectDisplayInfoRequest {
    const message = createBaseGetSubjectDisplayInfoRequest();
    message.subjectId = object.subjectId ?? "";
    return message;
  },
};

/** Service that provides display information for subjects. */
export type SubjectServiceDefinition = typeof SubjectServiceDefinition;
export const SubjectServiceDefinition = {
  name: "SubjectService",
  fullName: "reside.common.subject.v1.SubjectService",
  methods: {
    /** Returns display information for the provided subject identifier. */
    getSubjectDisplayInfo: {
      name: "GetSubjectDisplayInfo",
      requestType: GetSubjectDisplayInfoRequest as typeof GetSubjectDisplayInfoRequest,
      requestStream: false,
      responseType: SubjectDisplayInfo as typeof SubjectDisplayInfo,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface SubjectServiceImplementation<CallContextExt = {}> {
  /** Returns display information for the provided subject identifier. */
  getSubjectDisplayInfo(
    request: GetSubjectDisplayInfoRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<SubjectDisplayInfo>>;
}

export interface SubjectServiceClient<CallOptionsExt = {}> {
  /** Returns display information for the provided subject identifier. */
  getSubjectDisplayInfo(
    request: DeepPartial<GetSubjectDisplayInfoRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<SubjectDisplayInfo>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
